/**
 * Tests for src/adapters/opencode.js.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';

import {
  generateOpencodeAgentRecords,
  generateOpencodeArtifacts,
  renderOpencodeAgentMarkdown,
  renderOpencodeCommandMarkdown,
} from '../src/adapters/opencode.js';
import { parseFrontmatter } from '../src/frontmatter.js';
import { loadAgenticLoopConfig } from '../src/json.js';
import { seedTargetLayout } from './helpers/layout-fixture.js';

const REPO_ROOT = fileURLToPath(new URL('../', import.meta.url));

let tmpDir;

before(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'al-opencode-adapter-'));
});

after(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

function makeFixture() {
  const d = mkdtempSync(join(tmpDir, 'fx-'));
  seedTargetLayout(REPO_ROOT, d, { includeDocs: false, includeScratch: false });
  return d;
}

describe('generateOpencodeAgentRecords', () => {
  it('produces fixed OpenCode agents with per-role model settings', () => {
    const fx = makeFixture();
    const alConfig = loadAgenticLoopConfig(join(fx, 'agenticloop.json'));
    const agents = generateOpencodeAgentRecords(alConfig, fx);

    assert.deepEqual(Object.keys(agents), ['orchestrator', 'maintainer', 'engineer']);
    assert.equal(agents.orchestrator.mode, 'primary');
    assert.equal(agents.maintainer.mode, 'subagent');
    assert.equal(agents.engineer.mode, 'subagent');
    assert.equal(agents.orchestrator.model, alConfig.adapters.opencode.roleSettings.orchestrator.model);
    assert.equal(agents.maintainer.variant, alConfig.adapters.opencode.roleSettings.maintainer.reasoningEffort);
    assert.equal(agents.engineer.model, alConfig.adapters.opencode.roleSettings.engineer.model);
  });

  it('uses the configured skills source directory in prompt references', () => {
    const fx = makeFixture();
    const alConfig = loadAgenticLoopConfig(join(fx, 'agenticloop.json'));
    alConfig.skills = { sourceDirectory: 'process/skills' };

    const agents = generateOpencodeAgentRecords(alConfig, fx);

    assert.match(agents.orchestrator.prompt, /process\/skills\/role-delegation\/SKILL\.md/);
    assert.match(agents.orchestrator.prompt, /process\/skills\/blocked-state\/SKILL\.md/);
  });
});

describe('renderOpencodeAgentMarkdown', () => {
  it('renders orchestrator frontmatter with permissions and prompt references', () => {
    const fx = makeFixture();
    const alConfig = loadAgenticLoopConfig(join(fx, 'agenticloop.json'));
    const agent = generateOpencodeAgentRecords(alConfig, fx).orchestrator;
    const markdown = renderOpencodeAgentMarkdown(agent, 'orchestrator');
    const [frontmatter, body] = parseFrontmatter(markdown);

    assert.equal(frontmatter?.description, agent.description);
    assert.equal(frontmatter?.mode, 'primary');
    assert.equal(frontmatter?.model, agent.model);
    assert.equal(frontmatter?.variant, agent.variant);
    assert.equal(frontmatter?.permission?.edit, 'deny');
    assert.equal(frontmatter?.permission?.task?.['*'], 'deny');
    assert.equal(frontmatter?.permission?.task?.maintainer, 'allow');
    assert.equal(frontmatter?.permission?.task?.engineer, 'allow');
    assert.match(body, /Generated by Agentic Loop/);
    assert.match(body, /You are the Orchestrator for the target project\./);
    assert.match(body, /Follow agenticloop\/agents\/orchestrator\.md as the canonical role contract\./);
    assert.match(body, /\.agenticloop\/project\.md/);
    assert.match(body, /agenticloop\/skills\/role-delegation\/SKILL\.md/);
    assert.match(body, /agenticloop\/skills\/blocked-state\/SKILL\.md/);
    assert.match(body, /In OpenCode, use the Task tool or explicit @maintainer \/ @engineer invocation when available/);
  });

  it('renders subagent frontmatter without orchestrator permissions', () => {
    const fx = makeFixture();
    const alConfig = loadAgenticLoopConfig(join(fx, 'agenticloop.json'));
    const agent = generateOpencodeAgentRecords(alConfig, fx).engineer;
    const markdown = renderOpencodeAgentMarkdown(agent, 'engineer');
    const [frontmatter, body] = parseFrontmatter(markdown);

    assert.equal(frontmatter?.mode, 'subagent');
    assert.equal(frontmatter?.model, agent.model);
    assert.equal(frontmatter?.variant, agent.variant);
    assert.equal(frontmatter?.permission, undefined);
    assert.match(body, /agenticloop\/skills\/task-record-contract\/SKILL\.md/);
    assert.match(body, /agenticloop\/skills\/verification-evidence\/SKILL\.md/);
  });

  it('renders a backend-neutral engineer description without unconditional pull-request wording', () => {
    const fx = makeFixture();
    const alConfig = loadAgenticLoopConfig(join(fx, 'agenticloop.json'));
    const agent = generateOpencodeAgentRecords(alConfig, fx).engineer;
    const markdown = renderOpencodeAgentMarkdown(agent, 'engineer');
    const [frontmatter] = parseFrontmatter(markdown);

    assert.equal(frontmatter?.description, agent.description);
    assert.doesNotMatch(frontmatter?.description ?? '', /opens pull requests/i);
    assert.match(frontmatter?.description ?? '', /records implementation artifacts/i);
  });
});

describe('renderOpencodeCommandMarkdown', () => {
  it('binds the command to orchestrator without a model field', () => {
    const command = renderOpencodeCommandMarkdown();
    const [frontmatter, body] = parseFrontmatter(command);

    assert.equal(frontmatter?.agent, 'orchestrator');
    assert.equal(frontmatter?.model, undefined);
    assert.match(body, /\.agenticloop\/project\.md/);
    assert.match(body, /Create or refine the durable task record before any implementation\./);
    assert.match(body, /\$ARGUMENTS/);
  });
});

describe('generateOpencodeArtifacts', () => {
  it('writes only markdown agents and the OpenCode command', () => {
    const outputDir = join(tmpDir, 'generated');
    const fx = makeFixture();
    const alConfig = loadAgenticLoopConfig(join(fx, 'agenticloop.json'));

    const { files } = generateOpencodeArtifacts(alConfig, fx, outputDir);

    assert.deepEqual(files.sort(), [
      '.opencode/agents/engineer.md',
      '.opencode/agents/maintainer.md',
      '.opencode/agents/orchestrator.md',
      '.opencode/commands/agenticloop.md',
    ]);
    assert.equal(readFileSync(join(outputDir, '.opencode', 'agents', 'orchestrator.md'), 'utf-8').includes('mode: "primary"'), true);
    assert.equal(existsSync(join(outputDir, 'opencode.jsonc')), false);
  });
});
