/**
 * Tests for src/configure-models.js and src/adapter-discovery.js.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, readFileSync, rmSync, readdirSync, statSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { PassThrough } from 'node:stream';

import {
  configureModels,
  parseModelMutations,
  detectHost,
  validateHost,
  createPrompts,
  promptModelSettings,
} from '../src/configure-models.js';
import { getDefaultRoleSettings } from '../src/adapter-role-defaults.js';
import { adapterDiscoverySummary } from '../src/adapter-discovery.js';
import { loadJsonFile } from '../src/json.js';
import { seedTargetLayout } from './helpers/layout-fixture.js';

const REPO_ROOT = fileURLToPath(new URL('../', import.meta.url));
const BIN = join(REPO_ROOT, 'bin', 'agenticloop.js');

let tmpDir;

before(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'al-models-test-'));
});

after(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

function makeTarget() {
  const d = mkdtempSync(join(tmpDir, 'target-'));
  seedTargetLayout(REPO_ROOT, d);
  return d;
}

function writeOpencodeArtifactsFixture(dir) {
  mkdirSync(join(dir, '.opencode', 'agents'), { recursive: true });
  mkdirSync(join(dir, '.opencode', 'commands'), { recursive: true });
  writeFileSync(join(dir, '.opencode', 'agents', 'orchestrator.md'), '---\nmode: primary\nmodel: "m1"\n---\nbody\n');
  writeFileSync(join(dir, '.opencode', 'agents', 'maintainer.md'), '---\nmode: subagent\nmodel: "m2"\n---\nbody\n');
  writeFileSync(join(dir, '.opencode', 'agents', 'engineer.md'), '---\nmode: subagent\nmodel: "m3"\n---\nbody\n');
  writeFileSync(join(dir, '.opencode', 'commands', 'agenticloop.md'), '---\nagent: orchestrator\n---\nbody\n');
}

function writeCursorArtifactsFixture(dir) {
  mkdirSync(join(dir, '.cursor', 'agents'), { recursive: true });
  mkdirSync(join(dir, '.cursor', 'skills', 'agenticloop'), { recursive: true });
  writeFileSync(join(dir, '.cursor', 'agents', 'orchestrator.md'), [
    '---',
    'name: "orchestrator"',
    'description: "Coordinator"',
    'model: "m1"',
    'readonly: true',
    '---',
    '',
    '<!-- Generated by: agenticloop generate cursor. Do not edit by hand. -->',
    '',
  ].join('\n'));
  writeFileSync(join(dir, '.cursor', 'skills', 'agenticloop', 'SKILL.md'), [
    '---',
    'name: "agenticloop"',
    'description: "Explicit /agenticloop activation for Cursor."',
    'disable-model-invocation: true',
    '---',
    '',
    '<!-- Generated by: agenticloop generate cursor. Do not edit by hand. -->',
    '',
  ].join('\n'));
}

// ---------------------------------------------------------------------------
// parseModelMutations
// ---------------------------------------------------------------------------

describe('parseModelMutations', () => {
  it('parses role/model/reasoning-effort triples', () => {
    const args = [
      '--role', 'orchestrator',
      '--model', 'provider/model-a',
      '--reasoning-effort', 'high',
      '--role', 'engineer',
      '--model', 'provider/model-b',
    ];
    const mutations = parseModelMutations(args);
    assert.deepEqual(mutations, [
      { role: 'orchestrator', model: 'provider/model-a', reasoningEffort: 'high' },
      { role: 'engineer', model: 'provider/model-b' },
    ]);
  });

  it('returns empty array when no options are given', () => {
    assert.deepEqual(parseModelMutations([]), []);
  });
});

// ---------------------------------------------------------------------------
// configureModels
// ---------------------------------------------------------------------------

describe('configureModels', () => {
  it('writes adapter roleSettings to agenticloop.json', () => {
    const d = makeTarget();
    const result = configureModels(d, {
      adapter: 'opencode',
      mutations: [
        { role: 'orchestrator', model: 'openrouter/deepseek/deepseek-v4', reasoningEffort: 'high' },
        { role: 'engineer', model: 'openrouter/xiaomi/mimo', reasoningEffort: 'high' },
      ],
    });
    assert.deepEqual(result.errors, []);
    assert.ok(result.updated.includes('adapters.opencode.roleSettings.orchestrator.model'));


    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters?.opencode?.roleSettings?.orchestrator?.model, 'openrouter/deepseek/deepseek-v4');
    assert.equal(cfg.adapters?.opencode?.roleSettings?.orchestrator?.reasoningEffort, 'high');
    assert.equal(cfg.adapters?.opencode?.roleSettings?.engineer?.model, 'openrouter/xiaomi/mimo');
  });

  it('configures a non-interactive --role auditor model and preserves other roles', () => {
    const d = makeTarget();
    // Seed an explicit orchestrator model to prove it is preserved.
    configureModels(d, { adapter: 'opencode', mutations: [{ role: 'orchestrator', model: 'keep/me' }] });

    const result = configureModels(d, {
      adapter: 'opencode',
      mutations: parseModelMutations(['--role', 'auditor', '--model', 'openrouter/best-auditor', '--reasoning-effort', 'high']),
    });
    assert.deepEqual(result.errors, []);
    assert.ok(result.updated.includes('adapters.opencode.roleSettings.auditor.model'));

    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters.opencode.roleSettings.auditor.model, 'openrouter/best-auditor');
    assert.equal(cfg.adapters.opencode.roleSettings.auditor.reasoningEffort, 'high');
    assert.equal(cfg.adapters.opencode.roleSettings.orchestrator.model, 'keep/me');
  });

  it('errors when adapter is missing', () => {
    const d = makeTarget();
    const result = configureModels(d, { mutations: [{ role: 'orchestrator', model: 'x' }] });
    assert.ok(result.errors.some(e => e.includes('--adapter')));
  });

  it('errors when agenticloop.json is missing', () => {
    const d = mkdtempSync(join(tmpDir, 'no-config-'));
    const result = configureModels(d, { adapter: 'opencode', mutations: [{ role: 'orchestrator', model: 'x' }] });
    assert.ok(result.errors.some(e => e.includes('agenticloop.json not found')));
  });

  it('errors for unknown adapter', () => {
    const d = makeTarget();
    const result = configureModels(d, { adapter: 'unknown', mutations: [{ role: 'orchestrator', model: 'x' }] });
    assert.ok(result.errors.some(e => e.includes('Unknown adapter')));
  });

  it('rewrites agenticloop.json as formatted strict JSON', () => {
    const d = makeTarget();
    const cfgPath = join(d, 'agenticloop.json');
    writeFileSync(cfgPath, '{"extends":"./agenticloop/config.json","adapters":{"opencode":{"roleSettings":{}}}}\n', 'utf-8');

    const result = configureModels(d, {
      adapter: 'opencode',
      mutations: [{ role: 'engineer', model: 'configured/model', reasoningEffort: 'xhigh' }],
    });

    assert.deepEqual(result.errors, []);
    assert.deepEqual(result.warnings, []);
    const text = readFileSync(cfgPath, 'utf-8');
    assert.match(text, /^\{\n  "extends": "\.\/agenticloop\/config\.json",/);
    const cfg = loadJsonFile(cfgPath);
    assert.equal(cfg.adapters.opencode.roleSettings.engineer.model, 'configured/model');
    assert.equal(cfg.adapters.opencode.roleSettings.engineer.reasoningEffort, 'xhigh');
  });

  it('ignores reasoningEffort for Claude Code role settings', () => {
    const d = makeTarget();
    const result = configureModels(d, {
      adapter: 'claude-code',
      mutations: [
        { role: 'engineer', model: 'opus', reasoningEffort: 'max' },
      ],
    });

    assert.deepEqual(result.errors, []);
    assert.ok(result.warnings.some(w => w.includes('Skipping reasoningEffort for claude-code')));
    assert.ok(result.updated.includes('adapters.claude-code.roleSettings.engineer.model'));
    assert.ok(!result.updated.includes('adapters.claude-code.roleSettings.engineer.reasoningEffort'));

    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters['claude-code'].roleSettings.engineer.model, 'opus');
    assert.equal(cfg.adapters['claude-code'].roleSettings.engineer.reasoningEffort, undefined);
  });

  it('ignores reasoningEffort for Copilot role settings', () => {
    const d = makeTarget();
    const result = configureModels(d, {
      adapter: 'copilot',
      mutations: [
        { role: 'engineer', model: 'gpt-5.4', reasoningEffort: 'high' },
      ],
    });

    assert.deepEqual(result.errors, []);
    assert.ok(result.warnings.some(w => w.includes('Skipping reasoningEffort for copilot')));
    assert.ok(result.updated.includes('adapters.copilot.roleSettings.engineer.model'));
    assert.ok(!result.updated.includes('adapters.copilot.roleSettings.engineer.reasoningEffort'));

    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters.copilot.roleSettings.engineer.model, 'gpt-5.4');
    assert.equal(cfg.adapters.copilot.roleSettings.engineer.reasoningEffort, undefined);
  });

  it('ignores reasoningEffort for Cursor role settings', () => {
    const d = makeTarget();
    const result = configureModels(d, {
      adapter: 'cursor',
      mutations: [
        { role: 'engineer', model: 'gpt-5.5', reasoningEffort: 'high' },
      ],
    });

    assert.deepEqual(result.errors, []);
    assert.ok(result.warnings.some(w => w.includes('Skipping reasoningEffort for cursor')));
    assert.ok(result.updated.includes('adapters.cursor.roleSettings.engineer.model'));
    assert.ok(!result.updated.includes('adapters.cursor.roleSettings.engineer.reasoningEffort'));

    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters.cursor.roleSettings.engineer.model, 'gpt-5.5');
    assert.equal(cfg.adapters.cursor.roleSettings.engineer.reasoningEffort, undefined);
  });

  it('applies the recommended Codex profile without replacing explicit fields', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        codex: {
          roleSettings: {
            orchestrator: { model: 'custom-orchestrator' },
            maintainer: { reasoningEffort: 'minimal' },
          },
        },
      },
    }, null, 2) + '\n');

    const result = configureModels(d, { adapter: 'codex', profile: 'recommended' });

    assert.deepEqual(result.errors, []);
    assert.ok(result.updated.includes('adapters.codex.roleSettings.orchestrator.reasoningEffort'));
    assert.ok(result.preserved.includes('adapters.codex.roleSettings.orchestrator.model'));
    assert.ok(result.preserved.includes('adapters.codex.roleSettings.maintainer.reasoningEffort'));
    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters.codex.roleSettings.orchestrator.model, 'custom-orchestrator');
    assert.equal(cfg.adapters.codex.roleSettings.orchestrator.reasoningEffort, 'xhigh');
    assert.equal(cfg.adapters.codex.roleSettings.maintainer.model, 'gpt-5.6-terra');
    assert.equal(cfg.adapters.codex.roleSettings.maintainer.reasoningEffort, 'minimal');
    assert.deepEqual(cfg.adapters.codex.roleSettings.engineer, {
      model: 'gpt-5.6-terra',
      reasoningEffort: 'high',
    });
  });

  it('keeps default-profile objects isolated between callers', () => {
    const first = getDefaultRoleSettings('codex');
    first.engineer.model = 'changed';
    assert.equal(getDefaultRoleSettings('codex').engineer.model, 'gpt-5.6-terra');
    assert.deepEqual(getDefaultRoleSettings('unknown'), {});
  });

  it('reports added and preserved fields for the Codex recommended CLI profile', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: { codex: { roleSettings: { orchestrator: { model: 'custom' } } } },
    }, null, 2) + '\n');

    const result = spawnSync(process.execPath, [
      BIN, 'configure', 'models', '--target', d, '--adapter', 'codex', '--profile', 'recommended',
    ], { encoding: 'utf-8' });

    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /added: adapters\.codex\.roleSettings\.orchestrator\.reasoningEffort/);
    assert.match(result.stdout, /kept: adapters\.codex\.roleSettings\.orchestrator\.model/);
    assert.match(result.stdout, /agenticloop generate codex/);
  });

  it('rejects a recommended profile mixed with explicit model mutations', () => {
    const d = makeTarget();
    const result = spawnSync(process.execPath, [
      BIN, 'configure', 'models', '--target', d, '--adapter', 'codex', '--profile', 'recommended',
      '--role', 'engineer', '--model', 'other',
    ], { encoding: 'utf-8' });

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /cannot be combined/);
  });

  it('rejects the recommended profile for a non-Codex adapter', () => {
    const d = makeTarget();
    const result = spawnSync(process.execPath, [
      BIN, 'configure', 'models', '--target', d, '--adapter', 'opencode', '--profile', 'recommended',
    ], { encoding: 'utf-8' });

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /available only for --adapter codex/);
  });
});

// ---------------------------------------------------------------------------
// validateHost
// ---------------------------------------------------------------------------

describe('validateHost', () => {
  it('returns null for supported hosts', () => {
    assert.equal(validateHost('opencode'), null);
    assert.equal(validateHost('codex'), null);
    assert.equal(validateHost('claude-code'), null);
    assert.equal(validateHost('copilot'), null);
    assert.equal(validateHost('cursor'), null);
  });

  it('returns an error for unknown hosts', () => {
    const err = validateHost('unknown');
    assert.ok(err);
    assert.ok(err.includes('Unknown adapter'));
  });

  it('returns an error when host is missing', () => {
    const err = validateHost('');
    assert.ok(err);
    assert.ok(err.includes('--adapter'));
  });
});

// ---------------------------------------------------------------------------
// detectHost
// ---------------------------------------------------------------------------

describe('detectHost', () => {
  it('detects opencode from markdown agents and command', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-opencode-'));
    writeOpencodeArtifactsFixture(d);
    assert.deepEqual(detectHost(d), ['opencode']);
  });

  it('detects codex from .codex/agents', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-codex-'));
    mkdirSync(join(d, '.codex', 'agents'), { recursive: true });
    assert.deepEqual(detectHost(d), ['codex']);
  });

  it('detects codex from the public skill surface', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-codex-skill-'));
    mkdirSync(join(d, '.agents', 'skills', 'agenticloop'), { recursive: true });
    writeFileSync(join(d, '.agents', 'skills', 'agenticloop', 'SKILL.md'), '# Agentic Loop\n');
    assert.deepEqual(detectHost(d), ['codex']);
  });

  it('detects codex from plugin-root packaging', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-codex-plugin-root-'));
    mkdirSync(join(d, 'plugins', 'agenticloop', '.codex-plugin'), { recursive: true });
    writeFileSync(join(d, 'plugins', 'agenticloop', '.codex-plugin', 'plugin.json'), '{}\n');
    assert.deepEqual(detectHost(d), ['codex']);
  });

  it('detects claude-code from .claude/agents only', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-cc-'));
    mkdirSync(join(d, '.claude', 'agents'), { recursive: true });
    assert.deepEqual(detectHost(d), ['claude-code']);
  });

  it('detects copilot from generated .github artifacts only', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-copilot-'));
    mkdirSync(join(d, '.github', 'agents'), { recursive: true });
    mkdirSync(join(d, '.github', 'skills', 'agenticloop'), { recursive: true });
    mkdirSync(join(d, '.github', 'prompts'), { recursive: true });
    writeFileSync(join(d, '.github', 'agents', 'orchestrator.agent.md'), [
      '---',
      'name: "orchestrator"',
      'description: "Coordinator"',
      '---',
      '',
      '<!-- Generated by: agenticloop generate copilot. Do not edit by hand. -->',
      '',
    ].join('\n'));
    writeFileSync(join(d, '.github', 'skills', 'agenticloop', 'SKILL.md'), [
      '---',
      'name: "agenticloop"',
      'description: "Operate in Agentic Loop mode."',
      '---',
      '',
      '<!-- Generated by: agenticloop generate copilot. Do not edit by hand. -->',
      '',
    ].join('\n'));
    writeFileSync(join(d, '.github', 'prompts', 'agenticloop.prompt.md'), [
      '---',
      'description: "Prompt"',
      'agent: "orchestrator"',
      '---',
      '',
      '<!-- Generated by: agenticloop generate copilot. Do not edit by hand. -->',
      '',
    ].join('\n'));
    assert.deepEqual(detectHost(d), ['copilot']);
  });

  it('does not detect copilot from .github/copilot-instructions.md alone', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-copilot-instructions-only-'));
    mkdirSync(join(d, '.github'), { recursive: true });
    writeFileSync(join(d, '.github', 'copilot-instructions.md'), '# user-owned\n');
    assert.deepEqual(detectHost(d), []);
  });

  it('does not detect claude-code from .claude-plugin alone', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-cc-plugin-only-'));
    mkdirSync(join(d, '.claude-plugin'), { recursive: true });
    assert.deepEqual(detectHost(d), []);
  });

  it('detects multiple hosts', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-multi-'));
    writeOpencodeArtifactsFixture(d);
    mkdirSync(join(d, '.codex', 'agents'), { recursive: true });
    const detected = detectHost(d).sort();
    assert.deepEqual(detected, ['codex', 'opencode']);
  });

  it('detects cursor from generated .cursor artifacts only', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-cursor-'));
    writeCursorArtifactsFixture(d);
    assert.deepEqual(detectHost(d), ['cursor']);
  });

  it('returns empty array when no host artifacts exist', () => {
    const d = mkdtempSync(join(tmpDir, 'detect-none-'));
    assert.deepEqual(detectHost(d), []);
  });
});

// ---------------------------------------------------------------------------
// promptModelSettings
// ---------------------------------------------------------------------------

describe('createPrompts', () => {
  it('close() removes listeners and pauses the input stream', () => {
    const input = new PassThrough();
    let paused = false;
    const originalPause = input.pause.bind(input);
    input.pause = () => { paused = true; return originalPause(); };

    const prompts = createPrompts(input, { write: () => {} });

    assert.equal(input.listenerCount('data'), 1);
    assert.equal(input.listenerCount('end'), 1);

    prompts.close();

    assert.equal(input.listenerCount('data'), 0);
    assert.equal(input.listenerCount('end'), 0);
    assert.ok(paused, 'close() must pause the input stream');
  });

  it('close() tolerates streams without pause()', () => {
    const input = new PassThrough();
    input.pause = undefined;

    const prompts = createPrompts(input, { write: () => {} });
    prompts.close();

    assert.equal(input.listenerCount('data'), 0);
    assert.equal(input.listenerCount('end'), 0);
  });
});

describe('promptModelSettings', () => {
  it('resolves a pending prompt when stdin ends without a trailing newline', async () => {
    const input = new PassThrough();
    let output = '';
    const prompts = createPrompts(input, {
      write: (text) => { output += text; },
    });

    const answer = prompts.ask('model: ');
    input.end('provider/model');

    assert.equal(await answer, 'provider/model');
    assert.equal(output, 'model: ');
    prompts.close();
  });

  it('collects model and reasoning effort per role', async () => {
    const responses = ['model-a', 'high', '', 'model-b', ''];
    let i = 0;
    const prompts = {
      ask: async () => responses[i++],
    };
    const mutations = await promptModelSettings(['orchestrator', 'maintainer', 'engineer'], 'opencode', prompts);
    assert.deepEqual(mutations, [
      { role: 'orchestrator', model: 'model-a', reasoningEffort: 'high' },
      { role: 'engineer', model: 'model-b' },
    ]);
  });

  it('does not prompt for reasoning effort for Claude Code', async () => {
    const responses = ['sonnet', 'opus'];
    const questions = [];
    let i = 0;
    const prompts = {
      ask: async (question) => {
        questions.push(question);
        return responses[i++];
      },
    };

    const mutations = await promptModelSettings(['orchestrator', 'engineer'], 'claude-code', prompts);

    assert.deepEqual(mutations, [
      { role: 'orchestrator', model: 'sonnet' },
      { role: 'engineer', model: 'opus' },
    ]);
    assert.ok(questions.every(q => !q.includes('reasoning effort')));
  });

  it('does not prompt for reasoning effort for Copilot', async () => {
    const responses = ['gpt-5.4', 'gpt-5.5'];
    const questions = [];
    let i = 0;
    const prompts = {
      ask: async (question) => {
        questions.push(question);
        return responses[i++];
      },
    };

    const mutations = await promptModelSettings(['orchestrator', 'engineer'], 'copilot', prompts);

    assert.deepEqual(mutations, [
      { role: 'orchestrator', model: 'gpt-5.4' },
      { role: 'engineer', model: 'gpt-5.5' },
    ]);
    assert.ok(questions.every(q => !q.includes('reasoning effort')));
  });

  it('does not prompt for reasoning effort for Cursor', async () => {
    const responses = ['gpt-5.5', 'gpt-5.5-mini'];
    const questions = [];
    let i = 0;
    const prompts = {
      ask: async (question) => {
        questions.push(question);
        return responses[i++];
      },
    };

    const mutations = await promptModelSettings(['orchestrator', 'engineer'], 'cursor', prompts);

    assert.deepEqual(mutations, [
      { role: 'orchestrator', model: 'gpt-5.5' },
      { role: 'engineer', model: 'gpt-5.5-mini' },
    ]);
    assert.ok(questions.every(q => !q.includes('reasoning effort')));
  });

  it('prompts Codex with the supported reasoning effort values', async () => {
    const questions = [];
    const prompts = {
      ask: async (question) => {
        questions.push(question);
        return questions.length === 1 ? 'gpt-5.4' : 'xhigh';
      },
    };

    const mutations = await promptModelSettings(['engineer'], 'codex', prompts);

    assert.deepEqual(mutations, [
      { role: 'engineer', model: 'gpt-5.4', reasoningEffort: 'xhigh' },
    ]);
    assert.ok(questions.some(q => q.includes('minimal, low, medium, high, xhigh')));
  });

  it('returns empty array when all roles are skipped', async () => {
    const prompts = {
      ask: async () => '',
    };
    const mutations = await promptModelSettings(['orchestrator', 'maintainer'], 'opencode', prompts);
    assert.deepEqual(mutations, []);
  });
});

// ---------------------------------------------------------------------------
// adapterDiscoverySummary
// ---------------------------------------------------------------------------

describe('adapterDiscoverySummary', () => {
  it('reports no adapters before init', () => {
    const d = mkdtempSync(join(tmpDir, 'empty-'));
    const { adapters, nextSteps } = adapterDiscoverySummary(d);
    assert.deepEqual(adapters, []);
    assert.ok(nextSteps.some(s => s.includes('agenticloop init')));
  });

  it('reports configured adapters and missing model settings', () => {
    const d = makeTarget();
    // Replace target config with a clean one that has adapters but no models.
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        opencode: { roleSettings: {} },
        codex: { roleSettings: {} },
      },
    }, null, 2) + '\n');
    // Generate one adapter's artifacts so the summary recommends model config.
    writeOpencodeArtifactsFixture(d);

    const { adapters, nextSteps } = adapterDiscoverySummary(d);
    const opencode = adapters.find(a => a.host === 'opencode');
    assert.ok(opencode, 'opencode adapter should be reported');
    assert.deepEqual(opencode.missingModelRoles.sort(), ['auditor', 'engineer', 'maintainer', 'orchestrator']);
    assert.ok(
      nextSteps.some(s => s.includes('configure models') || s.includes('missing model')),
      'should suggest model configuration'
    );
  });

  it('does not claim all artifacts are present when optional adapters are absent', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        opencode: { roleSettings: {} },
        codex: { roleSettings: {} },
        'claude-code': { roleSettings: {} },
      },
    }, null, 2) + '\n');
    // No artifacts generated; all adapters are optional.

    const { nextSteps } = adapterDiscoverySummary(d);
    assert.ok(
      nextSteps.some(s => s.includes('No required adapter work is pending') && s.includes('Optional adapters have no generated artifacts')),
      'should note optional adapters have no artifacts'
    );
    assert.ok(
      !nextSteps.some(s => s.includes('All configured adapters have generated artifacts')),
      'should not claim all configured adapters have artifacts'
    );
  });

  it('does not treat generated skill copies alone as present host adapters', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        codex: { roleSettings: {} },
        'claude-code': { roleSettings: {} },
      },
    }, null, 2) + '\n');
    mkdirSync(join(d, '.agents', 'skills', 'agenticloop-role-delegation'), { recursive: true });
    mkdirSync(join(d, '.claude', 'skills', 'agenticloop'), { recursive: true });

    const { adapters, nextSteps } = adapterDiscoverySummary(d);
    const codex = adapters.find(a => a.host === 'codex');
    const claudeCode = adapters.find(a => a.host === 'claude-code');

    assert.deepEqual(codex?.present, []);
    assert.deepEqual(claudeCode?.present, []);
    assert.ok(
      nextSteps.some(s => s.includes('Optional adapters have no generated artifacts')),
      'skill-copy directories alone should not make optional host adapters look present'
    );
  });

  it('treats the single public Codex skill as present adapter output', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        codex: { roleSettings: {} },
      },
    }, null, 2) + '\n');
    mkdirSync(join(d, '.agents', 'skills', 'agenticloop'), { recursive: true });
    writeFileSync(join(d, '.agents', 'skills', 'agenticloop', 'SKILL.md'), '# Agentic Loop\n', 'utf-8');

    const { adapters } = adapterDiscoverySummary(d);
    const codex = adapters.find(a => a.host === 'codex');

    assert.deepEqual(codex?.present, ['.agents/skills/agenticloop/SKILL.md']);
  });

  it('does not treat root plugin packaging as repo-local Claude Code adapter output', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        'claude-code': { roleSettings: {} },
      },
    }, null, 2) + '\n');
    mkdirSync(join(d, '.claude-plugin'), { recursive: true });

    const { adapters, nextSteps } = adapterDiscoverySummary(d);
    const claudeCode = adapters.find(a => a.host === 'claude-code');

    assert.deepEqual(claudeCode?.present, []);
    assert.ok(
      nextSteps.some(s => s.includes('Optional adapters have no generated artifacts')),
      'root plugin packaging should not count as Mode B adapter output'
    );
  });

  it('recommends validate when required adapters are complete', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        opencode: {
          roleSettings: {
            orchestrator: { model: 'm1' },
            maintainer: { model: 'm2' },
            engineer: { model: 'm3' },
            auditor: { model: 'm4' },
          },
          enabled: true,
        },
      },
    }, null, 2) + '\n');
    writeOpencodeArtifactsFixture(d);

    const { nextSteps } = adapterDiscoverySummary(d);
    assert.ok(
      nextSteps.some(s => s.includes('agenticloop validate')),
      'should recommend validate when required work is complete'
    );
  });

  it('does not report inherited base adapters without artifacts', () => {
    const d = makeTarget();
    // Target config only has opencode, but base config has all adapters
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        opencode: {
          roleSettings: {
            orchestrator: { model: 'm1' },
            maintainer: { model: 'm2' },
            engineer: { model: 'm3' },
          },
        },
      },
    }, null, 2) + '\n');

    const { adapters } = adapterDiscoverySummary(d);
    const hosts = adapters.map(a => a.host);

    // Only opencode should be listed (the one explicitly in target config)
    // Inherited base adapters without artifacts should NOT appear
    for (const a of adapters) {
      if (a.host === 'opencode') continue;
      assert.ok(a.present.length > 0,
        `adapter ${a.host} has no artifacts and is not in target config - should not be listed`);
    }
  });
});
