/**
 * Lifecycle tests for src/remove.js — safe reversible removal.
 *
 * Covers:
 *   - Marker-based removal of generated artifacts
 *   - Claude agents with custom roleBindings filenames
 *   - Codex legacy skills require strong marker (not just name)
 *   - Claude settings reversal
 *   - Public skill directory preservation
 *   - Dry-run accuracy
 *   - Malformed marketplace JSON preservation
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import {
  existsSync,
  mkdirSync,
  mkdtempSync,
  readFileSync,
  readdirSync,
  rmSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';

import { removeAgenticLoop } from '../src/remove.js';

let tmpBase;

before(() => {
  tmpBase = mkdtempSync(join(tmpdir(), 'al-remove-test-'));
});

after(() => {
  rmSync(tmpBase, { recursive: true, force: true });
});

function makeTarget() {
  return mkdtempSync(join(tmpBase, 'target-'));
}

// ---------------------------------------------------------------------------
// Claude agents with custom filenames
// ---------------------------------------------------------------------------

describe('remove - Claude agents with custom roleBindings', () => {
  it('removes generated Claude agents with custom filenames', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.claude', 'agents'), { recursive: true });

    // Custom roleBindings: architect instead of orchestrator
    writeFileSync(join(t, '.claude', 'agents', 'architect.md'),
      '---\nname: "orchestrator"\n---\n\n<!-- Generated by: agenticloop generate claude-code -->\n\n# Architect');
    writeFileSync(join(t, '.claude', 'agents', 'coder.md'),
      '---\nname: "engineer"\n---\n\n<!-- Generated by: agenticloop generate claude-code -->\n\n# Coder');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.claude/agents/architect.md'));
    assert.ok(result.removed.includes('.claude/agents/coder.md'));
    assert.ok(!existsSync(join(t, '.claude', 'agents', 'architect.md')));
    assert.ok(!existsSync(join(t, '.claude', 'agents', 'coder.md')));
  });

  it('preserves unmarked Claude agents', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.claude', 'agents'), { recursive: true });

    writeFileSync(join(t, '.claude', 'agents', 'my-custom.md'), '# My Custom Agent');
    writeFileSync(join(t, '.claude', 'agents', 'orchestrator.md'),
      '<!-- Generated by: agenticloop generate claude-code -->\n# Orchestrator');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.claude/agents/orchestrator.md'));
    assert.ok(result.skipped.some(s => s.includes('.claude/agents/my-custom.md')));
    assert.ok(existsSync(join(t, '.claude', 'agents', 'my-custom.md')));
  });
});

// ---------------------------------------------------------------------------
// Codex legacy skills
// ---------------------------------------------------------------------------

describe('remove - Codex legacy skills require strong marker', () => {
  it('preserves a hand-authored skill named agenticloop-role-delegation', () => {
    const t = makeTarget();
    const skillDir = join(t, '.agents', 'skills', 'agenticloop-role-delegation');
    mkdirSync(skillDir, { recursive: true });
    // Hand-authored skill: no generated marker, no generated structure
    writeFileSync(join(skillDir, 'SKILL.md'), '# My Role Delegation Skill\nThis is hand-authored.');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.skipped.some(s => s.includes('agenticloop-role-delegation')));
    assert.ok(existsSync(join(skillDir, 'SKILL.md')));
  });

  it('removes a legacy skill with strong marker', () => {
    const t = makeTarget();
    const skillDir = join(t, '.agents', 'skills', 'agenticloop-role-delegation');
    mkdirSync(skillDir, { recursive: true });
    writeFileSync(join(skillDir, 'SKILL.md'),
      '# Skill\n<!-- Generated by: agenticloop generate codex. Do not edit by hand. -->');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.agents/skills/agenticloop-role-delegation'));
    assert.ok(!existsSync(skillDir));
  });

  it('removes a legacy skill with exact generated structure', () => {
    const t = makeTarget();
    const skillDir = join(t, '.agents', 'skills', 'agenticloop-role-delegation');
    mkdirSync(join(skillDir, 'agents'), { recursive: true });
    mkdirSync(join(skillDir, 'references', 'skills'), { recursive: true });
    writeFileSync(join(skillDir, 'SKILL.md'), '# Skill\nSome content');
    writeFileSync(join(skillDir, 'agents', 'openai.yaml'), 'name: test');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.agents/skills/agenticloop-role-delegation'));
  });
});

// ---------------------------------------------------------------------------
// Claude settings reversal
// ---------------------------------------------------------------------------

describe('remove - Claude settings reversal', () => {
  it('removes settings file when only Agentic Loop entries exist', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.claude'), { recursive: true });
    writeFileSync(join(t, '.claude', 'settings.json'), JSON.stringify({
      permissions: {
        allow: ['Bash(npx agenticloop *)', 'PowerShell(npx agenticloop *)'],
      },
    }, null, 2) + '\n');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.some(r => r.includes('settings.json')));
    assert.ok(!existsSync(join(t, '.claude', 'settings.json')));
  });

  it('removes only Agentic Loop entries from mixed settings', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.claude'), { recursive: true });
    writeFileSync(join(t, '.claude', 'settings.json'), JSON.stringify({
      permissions: {
        allow: [
          'Bash(git status *)',
          'Bash(npx agenticloop *)',
          'PowerShell(npx agenticloop *)',
        ],
      },
    }, null, 2) + '\n');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.some(r => r.includes('permission entries removed')));

    const remaining = JSON.parse(readFileSync(join(t, '.claude', 'settings.json'), 'utf-8'));
    assert.deepEqual(remaining.permissions.allow, ['Bash(git status *)']);
  });

  it('preserves settings with no Agentic Loop entries', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.claude'), { recursive: true });
    writeFileSync(join(t, '.claude', 'settings.json'), JSON.stringify({
      permissions: {
        allow: ['Bash(git status *)'],
      },
    }, null, 2) + '\n');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.skipped.some(s => s.includes('no Agentic Loop permission entries found')));
    assert.ok(existsSync(join(t, '.claude', 'settings.json')));
  });
});

// ---------------------------------------------------------------------------
// Marketplace malformed JSON
// ---------------------------------------------------------------------------

describe('remove - marketplace malformed JSON', () => {
  it('preserves malformed marketplace JSON byte-for-byte', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.agents', 'plugins'), { recursive: true });
    const malformed = '{ invalid json [[[ ]]}';
    writeFileSync(join(t, '.agents', 'plugins', 'marketplace.json'), malformed);

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.errors.some(e => e.includes('marketplace')));

    const content = readFileSync(join(t, '.agents', 'plugins', 'marketplace.json'), 'utf-8');
    assert.equal(content, malformed);
  });
});

// ---------------------------------------------------------------------------
// plugins/agenticloop ownership
// ---------------------------------------------------------------------------

describe('remove - plugins/agenticloop', () => {
  it('preserves plugins/agenticloop with unknown content', () => {
    const t = makeTarget();
    const pluginDir = join(t, 'plugins', 'agenticloop');
    mkdirSync(pluginDir, { recursive: true });
    writeFileSync(join(pluginDir, 'user-added.txt'), 'my content');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.skipped.some(s => s.includes('plugins/agenticloop')));
    assert.ok(existsSync(join(pluginDir, 'user-added.txt')));
  });
});

// ---------------------------------------------------------------------------
// Dry-run accuracy
// ---------------------------------------------------------------------------

describe('remove - dry-run', () => {
  it('dry-run reports same paths as real removal without deleting files', () => {
    const t1 = makeTarget();
    const t2 = makeTarget();

    for (const t of [t1, t2]) {
      mkdirSync(join(t, '.claude', 'agents'), { recursive: true });
      writeFileSync(join(t, '.claude', 'agents', 'orchestrator.md'),
        '<!-- Generated by: agenticloop generate claude-code -->\n# Orch');
      mkdirSync(join(t, '.opencode', 'agents'), { recursive: true });
      writeFileSync(join(t, '.opencode', 'agents', 'orchestrator.md'),
        '<!-- Generated by Agentic Loop. Do not edit by hand. Source: agenticloop.json (adapters.opencode.roleSettings). Refresh: agenticloop update --adapter opencode -->\n# Orch');
    }

    const dryResult = removeAgenticLoop({ target: t1, dryRun: true });
    const realResult = removeAgenticLoop({ target: t2, dryRun: false });

    // Dry-run reports the same file-level paths as real removal
    // (directory cleanup differs because dry-run doesn't empty directories)
    const isFileRemoved = p => {
      const lastSegment = p.split(/[\\/]/).pop() ?? '';
      // Files have an extension like .md, .toml, .json; directories like .claude don't
      return /\w+\.\w+$/.test(lastSegment);
    };
    const dryFiles = dryResult.removed.filter(isFileRemoved);
    const realFiles = realResult.removed.filter(isFileRemoved);
    assert.deepEqual(dryFiles.sort(), realFiles.sort());

    // Dry-run does NOT delete files
    assert.ok(existsSync(join(t1, '.claude', 'agents', 'orchestrator.md')));
    assert.ok(existsSync(join(t1, '.opencode', 'agents', 'orchestrator.md')));

    // Real removal DOES delete files
    assert.ok(!existsSync(join(t2, '.claude', 'agents', 'orchestrator.md')));
    assert.ok(!existsSync(join(t2, '.opencode', 'agents', 'orchestrator.md')));
  });
});

// ---------------------------------------------------------------------------
// Marker-based removal of generated artifacts (baseline)
// ---------------------------------------------------------------------------

describe('remove - marker-based removal baseline', () => {
  it('removes OpenCode agents with correct marker', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.opencode', 'agents'), { recursive: true });
    writeFileSync(join(t, '.opencode', 'agents', 'orchestrator.md'),
      '<!-- Generated by Agentic Loop. Do not edit by hand. Source: agenticloop.json (adapters.opencode.roleSettings). Refresh: agenticloop update --adapter opencode -->\n# Orchestrator');
    writeFileSync(join(t, '.opencode', 'agents', 'maintainer.md'),
      '<!-- Generated by Agentic Loop. Do not edit by hand. Source: agenticloop.json (adapters.opencode.roleSettings). Refresh: agenticloop update --adapter opencode -->\n# Maintainer');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.opencode/agents/orchestrator.md'));
    assert.ok(result.removed.includes('.opencode/agents/maintainer.md'));
  });

  it('removes Codex agents with correct marker', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.codex', 'agents'), { recursive: true });
    writeFileSync(join(t, '.codex', 'agents', 'orchestrator.toml'),
      '# Generated by: agenticloop generate codex\nname = "orchestrator"');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.codex/agents/orchestrator.toml'));
  });

  it('removes Copilot agents with correct marker', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.github', 'agents'), { recursive: true });
    writeFileSync(join(t, '.github', 'agents', 'orchestrator.agent.md'),
      '<!-- Generated by: agenticloop generate copilot. Do not edit by hand. -->\n# Orch');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.github/agents/orchestrator.agent.md'));
  });

  it('removes Cursor agents with correct marker', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.cursor', 'agents'), { recursive: true });
    writeFileSync(join(t, '.cursor', 'agents', 'orchestrator.md'),
      '<!-- Generated by: agenticloop generate cursor. Do not edit by hand. -->\n# Orch');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.removed.includes('.cursor/agents/orchestrator.md'));
  });

  it('preserves agents without correct marker', () => {
    const t = makeTarget();
    mkdirSync(join(t, '.opencode', 'agents'), { recursive: true });
    writeFileSync(join(t, '.opencode', 'agents', 'orchestrator.md'), '# My custom orchestrator');

    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.skipped.some(s => s.includes('.opencode/agents/orchestrator.md')));
    assert.ok(existsSync(join(t, '.opencode', 'agents', 'orchestrator.md')));
  });

  it('refuses to mutate package source repository', () => {
    // Use the actual repo root as target — should be refused.
    const t = join(import.meta.dirname, '..');
    const result = removeAgenticLoop({ target: t, dryRun: false });
    assert.ok(result.errors.some(e => e.includes('Refusing to mutate')));
  });
});
