/**
 * CLI-level tests for `node bin/agenticloop.js status`.
 */

import { describe, it, before, after } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, writeFileSync, rmSync, copyFileSync, readdirSync, statSync, existsSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { fileURLToPath } from 'node:url';
import { execSync, spawnSync } from 'node:child_process';
import { loadJsonFile } from '../src/json.js';
import { seedTargetLayout } from './helpers/layout-fixture.js';

const REPO_ROOT = fileURLToPath(new URL('../', import.meta.url));
const BIN = join(REPO_ROOT, 'bin', 'agenticloop.js');

let tmpDir;

before(() => {
  tmpDir = mkdtempSync(join(tmpdir(), 'al-status-cli-'));
});

after(() => {
  rmSync(tmpDir, { recursive: true, force: true });
});

function makeEmptyTarget() {
  return mkdtempSync(join(tmpDir, 'target-'));
}

function makeTarget() {
  const d = mkdtempSync(join(tmpDir, 'target-'));
  seedTargetLayout(REPO_ROOT, d);
  return d;
}

function writeOpencodeArtifactsFixture(dir) {
  mkdirSync(join(dir, '.opencode', 'agents'), { recursive: true });
  mkdirSync(join(dir, '.opencode', 'commands'), { recursive: true });
  writeFileSync(join(dir, '.opencode', 'agents', 'orchestrator.md'), '---\nmode: primary\nmodel: "m1"\n---\nbody\n');
  writeFileSync(join(dir, '.opencode', 'agents', 'maintainer.md'), '---\nmode: subagent\nmodel: "m2"\n---\nbody\n');
  writeFileSync(join(dir, '.opencode', 'agents', 'engineer.md'), '---\nmode: subagent\nmodel: "m3"\n---\nbody\n');
  writeFileSync(join(dir, '.opencode', 'commands', 'agenticloop.md'), '---\nagent: orchestrator\n---\nbody\n');
}

function writeCopilotArtifactsFixture(dir) {
  mkdirSync(join(dir, '.github', 'agents'), { recursive: true });
  mkdirSync(join(dir, '.github', 'skills', 'agenticloop'), { recursive: true });
  mkdirSync(join(dir, '.github', 'prompts'), { recursive: true });
  writeFileSync(join(dir, '.github', 'agents', 'orchestrator.agent.md'), [
    '---',
    'name: "orchestrator"',
    'description: "Coordinator"',
    '---',
    '',
    '<!-- Generated by: agenticloop generate copilot. Do not edit by hand. -->',
    '',
  ].join('\n'));
  writeFileSync(join(dir, '.github', 'skills', 'agenticloop', 'SKILL.md'), [
    '---',
    'name: "agenticloop"',
    'description: "Explicit /agenticloop activation for Copilot: Operate in Agentic Loop mode."',
    'user-invocable: true',
    'disable-model-invocation: true',
    '---',
    '',
    '<!-- Generated by: agenticloop generate copilot. Do not edit by hand. -->',
    '',
  ].join('\n'));
  writeFileSync(join(dir, '.github', 'prompts', 'agenticloop.prompt.md'), [
    '---',
    'description: "Prompt"',
    'agent: "orchestrator"',
    '---',
    '',
    '<!-- Generated by: agenticloop generate copilot. Do not edit by hand. -->',
    '',
  ].join('\n'));
}

function writeCursorArtifactsFixture(dir) {
  mkdirSync(join(dir, '.cursor', 'agents'), { recursive: true });
  mkdirSync(join(dir, '.cursor', 'skills', 'agenticloop'), { recursive: true });
  writeFileSync(join(dir, '.cursor', 'agents', 'orchestrator.md'), [
    '---',
    'name: "orchestrator"',
    'description: "Coordinator"',
    'model: "inherit"',
    'readonly: true',
    '---',
    '',
    '<!-- Generated by: agenticloop generate cursor. Do not edit by hand. -->',
    '',
  ].join('\n'));
  writeFileSync(join(dir, '.cursor', 'skills', 'agenticloop', 'SKILL.md'), [
    '---',
    'name: "agenticloop"',
    'description: "Explicit /agenticloop activation for Cursor."',
    'disable-model-invocation: true',
    '---',
    '',
    '<!-- Generated by: agenticloop generate cursor. Do not edit by hand. -->',
    '',
  ].join('\n'));
}

function status(target) {
  return execSync(`node "${BIN}" status --target "${target}"`, { encoding: 'utf-8' });
}

describe('status CLI', () => {
  it('reports no adapters before init', () => {
    const d = mkdtempSync(join(tmpDir, 'empty-'));
    const out = status(d);
    assert.ok(out.includes('agenticloop adapter discovery'));
    assert.ok(out.includes('agenticloop init'));
  });

  it('reports optional adapters with no artifacts accurately', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        opencode: { roleSettings: {} },
        codex: { roleSettings: {} },
      },
    }, null, 2) + '\n');

    const out = status(d);
    assert.ok(out.includes('Optional adapters have no generated artifacts'));
    assert.ok(!out.includes('All configured adapters have generated artifacts'));
  });

  it('recommends validate when required work is complete', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        opencode: {
          roleSettings: {
            orchestrator: { model: 'm1' },
            maintainer: { model: 'm2' },
            engineer: { model: 'm3' },
            auditor: { model: 'm4' },
          },
          enabled: true,
        },
      },
    }, null, 2) + '\n');
    writeOpencodeArtifactsFixture(d);

    const out = status(d);
    assert.ok(out.includes('agenticloop validate'));
  });

  it('reports Copilot artifacts when generated output is present', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        copilot: {
          enabled: true,
          roleSettings: {
            orchestrator: { model: 'gpt-5.4' },
            maintainer: { model: 'gpt-5.5' },
            engineer: { model: 'gpt-5.4-mini' },
            auditor: { model: 'gpt-5.5' },
          },
        },
      },
    }, null, 2) + '\n');
    writeCopilotArtifactsFixture(d);

    const out = status(d);
    assert.ok(out.includes('copilot: supported [required]'));
    assert.ok(out.includes('.github/agents/'));
    assert.ok(out.includes('.github/skills/agenticloop/SKILL.md'));
    assert.ok(out.includes('.github/prompts/agenticloop.prompt.md'));
    assert.ok(out.includes('/agenticloop'));
    assert.ok(out.includes('agenticloop validate'));
  });

  it('reports Cursor artifacts when generated output is present and suggests /agenticloop', () => {
    const d = makeTarget();
    writeFileSync(join(d, 'agenticloop.json'), JSON.stringify({
      extends: './agenticloop/config.json',
      adapters: {
        cursor: {
          enabled: true,
          roleSettings: {
            orchestrator: { model: 'gpt-5.5' },
            maintainer: { model: 'gpt-5.5-mini' },
            engineer: { model: 'gpt-5.5-codex' },
          },
        },
      },
    }, null, 2) + '\n');
    writeCursorArtifactsFixture(d);

    const out = status(d);
    assert.ok(out.includes('cursor: supported [required]'));
    assert.ok(out.includes('.cursor/agents/'));
    assert.ok(out.includes('.cursor/skills/agenticloop/SKILL.md'));
    assert.ok(out.includes('/agenticloop'));
  });

  it('init --setup --adapter opencode writes model settings and generates output', () => {
    const d = makeEmptyTarget();
    writeFileSync(join(d, 'AGENTS.md'), '# AGENTS\n');
    writeFileSync(join(d, 'README.md'), '# README\n');
    writeFileSync(join(d, 'IMPLEMENTATION_PLAN.md'), '# Plan\n');

    const input = ['openrouter/model-o', 'high', 'openrouter/model-m', 'high', 'openrouter/model-e', 'high', ''].join('\n');
    execSync(`node "${BIN}" init --target "${d}" --adapter opencode --setup`, {
      encoding: 'utf-8',
      input,
    });

    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters?.opencode?.roleSettings?.orchestrator?.model, 'openrouter/model-o');
    assert.equal(cfg.adapters?.opencode?.roleSettings?.maintainer?.model, 'openrouter/model-m');
    assert.equal(cfg.adapters?.opencode?.roleSettings?.engineer?.model, 'openrouter/model-e');
    assert.ok(existsSync(join(d, '.opencode', 'agents', 'orchestrator.md')), 'OpenCode orchestrator agent should be generated after setup');
    assert.ok(!existsSync(join(d, 'opencode.jsonc')), 'opencode.jsonc should not be generated after setup');
    assert.ok(existsSync(join(d, '.opencode', 'commands', 'agenticloop.md')), 'OpenCode command should be generated after setup');
  });

  it('init --setup --adapter copilot writes model settings and generates Copilot output', () => {
    const d = makeEmptyTarget();
    writeFileSync(join(d, 'AGENTS.md'), '# AGENTS\n');
    writeFileSync(join(d, 'README.md'), '# README\n');
    writeFileSync(join(d, 'IMPLEMENTATION_PLAN.md'), '# Plan\n');

    const input = ['gpt-5.4', 'gpt-5.5', 'gpt-5.4-mini', ''].join('\n');
    execSync(`node "${BIN}" init --target "${d}" --adapter copilot --setup`, {
      encoding: 'utf-8',
      input,
    });

    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters?.copilot?.roleSettings?.orchestrator?.model, 'gpt-5.4');
    assert.equal(cfg.adapters?.copilot?.roleSettings?.maintainer?.model, 'gpt-5.5');
    assert.equal(cfg.adapters?.copilot?.roleSettings?.engineer?.model, 'gpt-5.4-mini');
    assert.ok(existsSync(join(d, '.github', 'agents', 'orchestrator.agent.md')));
    assert.ok(existsSync(join(d, '.github', 'skills', 'agenticloop', 'SKILL.md')));
    assert.ok(existsSync(join(d, '.github', 'prompts', 'agenticloop.prompt.md')));
    assert.ok(!existsSync(join(d, '.github', 'copilot-instructions.md')));
  });

  it('init --setup --adapter cursor writes model settings and generates Cursor output', () => {
    const d = makeEmptyTarget();
    writeFileSync(join(d, 'AGENTS.md'), '# AGENTS\n');
    writeFileSync(join(d, 'README.md'), '# README\n');
    writeFileSync(join(d, 'IMPLEMENTATION_PLAN.md'), '# Plan\n');

    const input = ['gpt-5.5', 'gpt-5.5-mini', 'gpt-5.5-codex', ''].join('\n');
    execSync(`node "${BIN}" init --target "${d}" --adapter cursor --setup`, {
      encoding: 'utf-8',
      input,
    });

    const cfg = loadJsonFile(join(d, 'agenticloop.json'));
    assert.equal(cfg.adapters?.cursor?.roleSettings?.orchestrator?.model, 'gpt-5.5');
    assert.equal(cfg.adapters?.cursor?.roleSettings?.maintainer?.model, 'gpt-5.5-mini');
    assert.equal(cfg.adapters?.cursor?.roleSettings?.engineer?.model, 'gpt-5.5-codex');
    assert.ok(existsSync(join(d, '.cursor', 'agents', 'orchestrator.md')));
    assert.ok(existsSync(join(d, '.cursor', 'skills', 'agenticloop', 'SKILL.md')));
    assert.ok(!existsSync(join(d, '.cursor', 'rules')));
  });

  it('rejects init --setup --adapter all because setup needs one host', () => {
    const d = makeEmptyTarget();
    const result = spawnSync(process.execPath, [
      BIN,
      'init',
      '--target',
      d,
      '--adapter',
      'all',
      '--setup',
    ], { encoding: 'utf-8' });

    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /requires one concrete adapter/);
    assert.ok(!existsSync(join(d, 'agenticloop.json')), 'init should not scaffold after rejecting setup all');
  });
});
