/**
 * GitHub Copilot host adapter.
 *
 * Status: supported.
 *
 * Repo-local Copilot MVP support focuses on explicit slash activation plus one
 * public Agentic Loop skill surface:
 *   - Custom agents under .github/agents/*.agent.md.
 *   - One public .github/skills/agenticloop/SKILL.md skill.
 *   - Internal procedure references under
 *     .github/skills/agenticloop/references/.
 *   - One IDE prompt-file fallback under .github/prompts/agenticloop.prompt.md.
 *
 * This MVP intentionally does NOT generate .github/copilot-instructions.md.
 * Repository-wide and path-specific Copilot instructions remain user or
 * team-owned surfaces.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { parseFrontmatter } from '../frontmatter.js';
import {
  PROCESS_DOC_RELATIVE_PATH,
  bundledToolkitPath,
} from '../layout.js';
import {
  AGENTIC_LOOP_OPERATION_DESCRIPTION,
  dualModePreambleLines,
  isDualModeRole,
  buildRoleRecord,
  readCanonicalBackendEntries,
  readCanonicalSkillEntries,
  resolveRoleModel,
  planReferenceTree,
} from './shared.js';
import { emptyAdapterSlot, fillUnsupportedActivationSlots } from '../adapter-slots.js';
import {
  buildEffectiveHostRoleCapabilityInventory,
  hostRoleCapabilitySidecarRelativePath,
  renderHostRoleCapabilityNotice,
  renderHostRoleCapabilitySidecar,
} from '../host-role-capabilities.js';
import {
  getWorkflowRoleLabel,
  WORKFLOW_ROLE_IDS,
} from '../workflow-roles.js';

const COPILOT_START_COMMAND = bundledToolkitPath('agenticloop/commands/start.md');
export const COPILOT_ACTIVATION_ADAPTER_ID = 'copilot.prompt.input.v1';

/**
 * The one Copilot activation declaration.
 *
 * Copilot has two activation surfaces - the public `.github/skills/agenticloop/`
 * skill and the `.github/prompts/agenticloop.prompt.md` IDE fallback - and both
 * fill their slots from this single object. Declaring the capability twice is how
 * the prompt previously drifted into carrying no typed declaration at all while
 * the skill carried a complete one, leaving a live activation surface that
 * claimed nothing about its capture capability.
 */
const COPILOT_ACTIVATION_DECLARATION = Object.freeze({
  adapterId: COPILOT_ACTIVATION_ADAPTER_ID,
  limitation: 'Copilot prompt input is visible to the delegated model and is not a host-owned capture channel.',
  requestedInput: 'Requested task or context: use the current user request or selected task id as advisory context.',
});

export const COPILOT_PUBLIC_SKILL_NAME = 'agenticloop';
export const COPILOT_GENERATED_MARKER = 'Generated by: agenticloop generate copilot';
export const COPILOT_PROMPT_RELATIVE_PATH = '.github/prompts/agenticloop.prompt.md';
export const COPILOT_SKILL_RELATIVE_PATH =
  `.github/skills/${COPILOT_PUBLIC_SKILL_NAME}/SKILL.md`;
export const COPILOT_REQUIRED_PUBLIC_REFERENCES = [
  'role-delegation',
  'task-record-contract',
  'setup-agenticloop',
  'blocked-state',
];

function quoteYamlScalar(value) {
  return JSON.stringify(String(value));
}

function replaceAll(value, search, replacement) {
  return value.split(search).join(replacement);
}

function copilotSkillReferenceRelativePath(canonicalName) {
  return `references/skills/${canonicalName}/reference.md`;
}

function copilotSkillReferenceAbsolutePath(canonicalName) {
  return `.github/skills/${COPILOT_PUBLIC_SKILL_NAME}/references/skills/${canonicalName}/reference.md`;
}

function copilotBackendReferenceRelativePath(filename) {
  return `references/backends/${filename}`;
}

function copilotBackendReferenceAbsolutePath(filename) {
  return `.github/skills/${COPILOT_PUBLIC_SKILL_NAME}/references/backends/${filename}`;
}

function buildSkillReferenceMap(entries, pathBuilder) {
  const map = new Map();
  for (const entry of entries) {
    map.set(entry.canonicalName, pathBuilder(entry.canonicalName));
  }
  return map;
}

function addBackendReferencesToMap(map, backendEntries, pathBuilder) {
  for (const entry of backendEntries) {
    map.set(`backends/${entry.filename}`, pathBuilder(entry.filename));
    map.set(`agenticloop/backends/${entry.filename}`, pathBuilder(entry.filename));
  }
}

function skillReferencePath(skillReferenceMap, canonicalName, pathBuilder) {
  return skillReferenceMap.get(canonicalName) ?? pathBuilder(canonicalName);
}

function rewriteCopilotSkillReferences(text, skillReferenceMap) {
  let rewritten = text.replace(/\[\[([A-Za-z0-9_.-]+)\]\]/g, (full, name) => {
    const mapped = skillReferenceMap.get(name);
    return mapped ? `\`${mapped}\`` : full;
  });

  for (const [canonicalName, mappedPath] of skillReferenceMap.entries()) {
    rewritten = replaceAll(rewritten, `\`${canonicalName}\``, `\`${mappedPath}\``);
    rewritten = replaceAll(
      rewritten,
      `\`skills/${canonicalName}/SKILL.md\``,
      `\`${mappedPath}\``
    );
    rewritten = replaceAll(
      rewritten,
      `\`agenticloop/skills/${canonicalName}/SKILL.md\``,
      `\`${mappedPath}\``
    );
  }

  return rewritten;
}

function renderCopilotGeneratedText(text, skillReferenceMap) {
  return rewriteCopilotSkillReferences(text, skillReferenceMap);
}

function renderReferenceMarkdown(sourceText, skillReferenceMap) {
  return renderCopilotGeneratedText(sourceText, skillReferenceMap);
}

function copyCopilotReferenceTree(
  sourceDir,
  destDir,
  outputDir,
  skillReferenceMap,
  copied,
  currentSrc = sourceDir,
  currentDest = destDir
) {
  mkdirSync(currentDest, { recursive: true });

  for (const entry of readdirSync(currentSrc)) {
    const sourceEntry = join(currentSrc, entry);
    const entryStat = statSync(sourceEntry);

    if (entryStat.isDirectory()) {
      copyCopilotReferenceTree(
        sourceDir,
        destDir,
        outputDir,
        skillReferenceMap,
        copied,
        sourceEntry,
        join(currentDest, entry)
      );
      continue;
    }

    const destName = entry === 'SKILL.md' ? 'reference.md' : entry;
    const destEntry = join(currentDest, destName);

    if (entry === 'SKILL.md') {
      const rendered = renderReferenceMarkdown(
        readFileSync(sourceEntry, 'utf-8'),
        skillReferenceMap
      );
      writeFileSync(destEntry, rendered, 'utf-8');
    } else {
      copyFileSync(sourceEntry, destEntry);
    }

    copied.push(relative(outputDir, destEntry).replace(/\\/g, '/'));
  }
}

function writeCopilotSkillReferences(skillEntries, skillReferenceMap, destRoot, outputDir) {
  mkdirSync(destRoot, { recursive: true });
  const copied = [];

  for (const entry of skillEntries) {
    const destDir = join(destRoot, entry.canonicalName);
    copyCopilotReferenceTree(entry.sourceDir, destDir, outputDir, skillReferenceMap, copied);
  }

  return copied;
}

function writeCopilotBackendReferences(backendEntries, destRoot, outputDir, skillReferenceMap) {
  mkdirSync(destRoot, { recursive: true });
  const copied = [];

  for (const entry of backendEntries) {
    const destFile = join(destRoot, entry.filename);
    const rendered = renderCopilotGeneratedText(
      readFileSync(entry.sourceFile, 'utf-8'),
      skillReferenceMap
    );
    writeFileSync(destFile, rendered, 'utf-8');
    copied.push(relative(outputDir, destFile).replace(/\\/g, '/'));
  }

  return copied;
}

function loadCopilotStartCommandBody() {
  const source = readFileSync(COPILOT_START_COMMAND, 'utf-8');
  const [, body] = parseFrontmatter(source);
  return body.trim();
}

function replaceRequiredTemplateText(text, search, replacement, label) {
  if (!text.includes(search)) {
    throw new Error(
      `Copilot start command template drift: expected ${label} text in commands/start.md`
    );
  }
  return text.replace(search, replacement);
}

function buildCopilotInternalReferenceIndexLines(skillReferenceMap, backendEntries) {
  const lines = ['Internal Agentic Loop references:'];
  for (const skillName of COPILOT_REQUIRED_PUBLIC_REFERENCES) {
    lines.push(
      `- ${skillName}: \`${skillReferencePath(skillReferenceMap, skillName, copilotSkillReferenceRelativePath)}\``
    );
  }
  for (const entry of backendEntries) {
    const name = entry.filename === 'README.md'
      ? 'backend/index'
      : `backend/${entry.filename.replace(/\.md$/, '')}`;
    lines.push(`- ${name}: \`${copilotBackendReferenceRelativePath(entry.filename)}\``);
  }
  return lines;
}

function renderCopilotPublicSkill(skillReferenceMap, agentNames, backendEntries) {
  const setupReferencePath = skillReferencePath(
    skillReferenceMap,
    'setup-agenticloop',
    copilotSkillReferenceRelativePath
  );
  const roleDelegationReferencePath = skillReferencePath(
    skillReferenceMap,
    'role-delegation',
    copilotSkillReferenceRelativePath
  );
  const blockedStateReferencePath = skillReferencePath(
    skillReferenceMap,
    'blocked-state',
    copilotSkillReferenceRelativePath
  );
  const maintainerAgent = agentNames.maintainer ?? 'maintainer';
  const engineerAgent = agentNames.engineer ?? 'engineer';
  let body = loadCopilotStartCommandBody();
  body = fillUnsupportedActivationSlots(body, COPILOT_ACTIVATION_DECLARATION);

  body = replaceRequiredTemplateText(
    body,
    'confirmed map lacks a valid human-confirmed `development_stage`, route\n`agenticloop/skills/setup-agenticloop/SKILL.md` or confirm the profile before\nselecting or creating the first task.',
    `confirmed map lacks a valid human-confirmed \`development_stage\`, route \`${setupReferencePath}\` or confirm the profile before\nselecting or creating the first task.`,
    'setup routing'
  );

  body = replaceRequiredTemplateText(
    body,
    'Keep the main session as the coordinator: it reads the selected project config\nand process docs, routes task authoring, review, acceptance, and closeout\nthrough the maintainer role, routes scoped implementation and revision work\nthrough the engineer role, and should not directly edit implementation files\nunless the human explicitly asks. Respect the Advance Authorization Boundary,\nblocked-state handling, decision records, event logging rules, and configured\ngroup approval gates.',
    `Keep the active Copilot session as the coordinator/orchestrator. It reads the selected project config\nand process docs, routes task authoring, review, acceptance, and closeout\nthrough the Copilot custom agent \`${maintainerAgent}\`, routes scoped implementation and revision work\nthrough the Copilot custom agent \`${engineerAgent}\`, and should not directly edit implementation files from the coordinator unless the human explicitly asks.\n\nUse real Copilot custom-agent, subagent, or handoff delegation where the current surface supports it. If delegation is unavailable after a capability check, record a bounded fallback reason and continue according to \`${roleDelegationReferencePath}\`.\n\nFollow \`${roleDelegationReferencePath}\` for delegation capability checks, backend enforcement, bounded fallback, and \`role.invoked\` event logging. Respect the Advance Authorization Boundary, \`${blockedStateReferencePath}\`, decision records, event logging rules, and configured group approval gates.`,
    'coordinator delegation'
  );

  body = renderCopilotGeneratedText(body, skillReferenceMap);

  const description =
    `Explicit /agenticloop activation for Copilot: ${AGENTIC_LOOP_OPERATION_DESCRIPTION}`;

  return [
    '---',
    `name: ${quoteYamlScalar(COPILOT_PUBLIC_SKILL_NAME)}`,
    `description: ${quoteYamlScalar(description)}`,
    'user-invocable: true',
    'disable-model-invocation: true',
    '---',
    '',
    `<!-- ${COPILOT_GENERATED_MARKER}. Do not edit by hand. -->`,
    '',
    body,
    '',
    ...buildCopilotInternalReferenceIndexLines(skillReferenceMap, backendEntries),
    '',
  ].join('\n');
}

function formatRequiredSkillLines(requiredSkills, skillReferenceMap) {
  return (requiredSkills ?? []).map(skillName => {
    const referencePath = skillReferencePath(
      skillReferenceMap,
      skillName,
      copilotSkillReferenceAbsolutePath
    );
    return `- \`${skillName}\`: \`${referencePath}\``;
  });
}

function firstRoleParagraph(roleBody) {
  for (const line of (roleBody ?? '').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    return trimmed;
  }
  return '';
}

function buildCopilotAgentBody(
  roleName,
  roleSourceFile,
  requiredSkills,
  roleBody,
  skillReferenceMap,
  agentNames,
  capabilityInventory
) {
  const maintainerAgent = agentNames.maintainer ?? 'maintainer';
  const engineerAgent = agentNames.engineer ?? 'engineer';
  const auditorAgent = agentNames.auditor ?? 'auditor';
  const roleDelegationReferencePath = skillReferencePath(
    skillReferenceMap,
    'role-delegation',
    copilotSkillReferenceAbsolutePath
  );
  const dualMode = isDualModeRole(roleName);
  const lines = [];
  lines.push(`You are the Agentic Loop ${getWorkflowRoleLabel(roleName)} custom agent for the target project in GitHub Copilot.`);
  lines.push(`Canonical role source: \`${roleSourceFile}\`.`);
  // Dual-mode roles must select their mode before any workflow-state instruction,
  // otherwise the prompt orders a standalone delegation to adopt the methodology.
  if (dualMode) {
    lines.push(...dualModePreambleLines(roleName));
  }
  lines.push(`${dualMode ? 'In Agentic Loop mode: ' : ''}Read \`.agenticloop/project.md\` before acting for setup status, task backend, document selections, naming, grouping, and event logging.`);
  lines.push(`${dualMode ? 'In Agentic Loop mode: ' : ''}Follow \`${PROCESS_DOC_RELATIVE_PATH}\` as the workflow methodology.${dualMode ? ' In standalone mode, follow the parent request and the target repository rules instead.' : ''}`);
  lines.push('Path convention: toolkit source (agents/, skills/, backends/) lives under agenticloop/ (no leading dot); target project state (project.md, tasks/, decisions/, improvements/) lives under .agenticloop/ (leading dot). .agenticloop/agents, .agenticloop/skills, and .agenticloop/backends are invalid paths.');

  const skillLines = formatRequiredSkillLines(requiredSkills, skillReferenceMap);
  if (skillLines.length > 0) {
    lines.push('Agentic Loop internal references to use when their trigger applies:');
    lines.push(...skillLines);
  }

  if (roleName === 'orchestrator') {
    lines.push(`When maintainer-owned work is needed, delegate through the Copilot custom agent \`${maintainerAgent}\`. When engineer-owned work is needed, delegate through the Copilot custom agent \`${engineerAgent}\` instead of doing that work inline.`);
    lines.push(`When the covered tasks of a work unit are accepted and integrated into one exact frozen candidate, delegate work-unit certification through the Copilot custom agent \`${auditorAgent}\`. Every re-audit is a fresh delegation; a same-session audit does not satisfy work-unit auditing. Persist the returned \`auditor_report_v1\` object through \`agenticloop audit report\` without rewriting its findings.`);
    lines.push('Agentic Loop is serial by default. For every authorized multi-task unit, complete a current Parallel Opportunity Scan after decomposition and include its durable result or not-currently-eligible rescan trigger in implementation delegation. Load parallel-delegation before choosing serial or parallel execution.');
    lines.push('Start parallel role work only when the parallel-delegation skill plan, lease, backend ownership, and join condition requirements are satisfied; otherwise record the concrete serial reason.');
    lines.push('Use real Copilot custom-agent, subagent, or handoff delegation where the current surface supports it.');
    lines.push(`If delegation is unavailable after a capability check, record a bounded fallback reason and continue according to \`${roleDelegationReferencePath}\`.`);
    lines.push('For long-running or parallel delegated work, include the lease with an observable-step checkpoint cadence and require a status return at the progress checkpoint, stop condition, wrong branch/worktree, or no-progress budget.');
    lines.push('When event logging is enabled, emit `role.invoked` after a real role invocation or explicit fallback role assumption.');
    lines.push('Keep this Copilot session as the coordinator/orchestrator and do not directly edit implementation files unless the human explicitly asks.');
  } else if (roleName === 'maintainer') {
    lines.push('In Agentic Loop mode: Stay within maintainer boundaries and own setup confirmation, task records, review, acceptance, follow-up triage, and closeout.');
    lines.push('In Agentic Loop mode, honor any delegation lease from the orchestrator, including any observable-step checkpoint cadence, and return status when the lease, stop condition, collision, or no-progress budget requires it.');
    lines.push('In standalone mode, perform bounded planning or review and return advisory output without Agentic Loop workflow state or authority.');
    lines.push('Do not implement code changes. The canonical Maintainer Review Fixup is available only in Agentic Loop mode under its bounded contract. Stop and hand control back after producing maintainer output for the orchestrator, parent, or human.');
  } else if (roleName === 'engineer') {
    lines.push('In Agentic Loop mode, honor any delegation lease from the orchestrator, including any observable-step checkpoint cadence, and return status when the lease, stop condition, wrong branch/worktree, collision, or no-progress budget requires it. Stop and hand control back once implementation evidence is ready for maintainer review.');
  } else if (roleName === 'auditor') {
    lines.push('You are read-only with respect to implementation, tests, configuration, product documentation, commits, branches, pull requests, task acceptance, product decisions, and risk acceptance. The `edit` tool is withheld from this agent; do not attempt to work around it.');
    lines.push('Inspect the repository, the assessed artifact, task records, decisions, and evidence, and run only safe bounded non-publishing verification. Do not implement remediation, accept or reopen tasks, expand scope, change accepted decisions, or accept a limitation or risk for the human.');
    lines.push('In Agentic Loop mode, audit the exact frozen candidate named in the packet against its covered-task set, cover all six perspectives, and return one consolidated `auditor_report_v1` object with exactly one verdict to the orchestrator. Persistence into the audit record is mechanical and belongs to the orchestrator or the `agenticloop audit` CLI; never edit the audit record or any task record yourself.');
  }

  lines.push('');
  lines.push(renderHostRoleCapabilityNotice('copilot', roleName, capabilityInventory));
  lines.push('');
  lines.push('Canonical role contract follows:');
  lines.push('');
  const renderedRoleBody = renderCopilotGeneratedText(roleBody, skillReferenceMap);
  if (renderedRoleBody) {
    lines.push(renderedRoleBody);
  }
  const firstParagraph = firstRoleParagraph(roleBody);
  if (firstParagraph && !renderedRoleBody.includes(firstParagraph)) {
    lines.push('');
    lines.push(firstParagraph);
  }
  return lines.join('\n');
}

function agentToolsForRole(roleName) {
  if (roleName === 'orchestrator') {
    return ['agent', 'execute', 'read', 'search'];
  }
  // Auditor keeps read/search/execute so it can inspect evidence and run bounded
  // non-publishing checks, but `edit` is withheld: the read-only posture is
  // enforced by the tool grant, not only by prompt text.
  if (roleName === 'auditor') {
    return ['execute', 'read', 'search'];
  }
  return ['execute', 'read', 'search', 'edit'];
}

function subagentAllowListForRole(roleName, agentNames) {
  if (roleName !== 'orchestrator') return [];
  return [
    agentNames.maintainer ?? 'maintainer',
    agentNames.engineer ?? 'engineer',
    agentNames.auditor ?? 'auditor',
  ];
}

function userInvocableForRole(roleName) {
  return roleName === 'orchestrator';
}

function disableModelInvocationForRole(roleName) {
  return roleName === 'orchestrator';
}

function renderToolsFrontmatter(lines, tools) {
  lines.push('tools:');
  for (const toolName of tools) {
    lines.push(`  - ${quoteYamlScalar(toolName)}`);
  }
}

function renderStringListFrontmatter(lines, fieldName, values) {
  if (!values || values.length === 0) return;
  lines.push(`${fieldName}:`);
  for (const value of values) {
    lines.push(`  - ${quoteYamlScalar(value)}`);
  }
}

function renderCopilotAgentMarkdown(
  agentName,
  roleName,
  roleRecord,
  modelSettings,
  skillReferenceMap,
  agentNames,
  capabilityInventory
) {
  const lines = [];
  const tools = agentToolsForRole(roleName);
  const agents = subagentAllowListForRole(roleName, agentNames);
  lines.push('---');
  lines.push(`name: ${quoteYamlScalar(agentName)}`);
  if (roleRecord.description) {
    lines.push(`description: ${quoteYamlScalar(roleRecord.description.replace(/\n+/g, ' '))}`);
  }
  renderToolsFrontmatter(lines, tools);
  renderStringListFrontmatter(lines, 'agents', agents);
  if (modelSettings.model) {
    lines.push(`model: ${quoteYamlScalar(modelSettings.model)}`);
  }
  lines.push(`user-invocable: ${userInvocableForRole(roleName) ? 'true' : 'false'}`);
  lines.push(`disable-model-invocation: ${disableModelInvocationForRole(roleName) ? 'true' : 'false'}`);
  lines.push('---');
  lines.push('');
  lines.push(`<!-- ${COPILOT_GENERATED_MARKER}. Do not edit by hand. -->`);
  lines.push('');
  lines.push(buildCopilotAgentBody(
    roleName,
    roleRecord.sourceFile,
    roleRecord.requiredSkills,
    roleRecord.promptBody,
    skillReferenceMap,
    agentNames,
    capabilityInventory
  ));
  lines.push('');
  return lines.join('\n');
}

/**
 * Render the Copilot IDE prompt-file fallback.
 *
 * This is a live activation surface, so it carries the same typed Copilot
 * activation declaration as the public skill, built from the shared
 * `COPILOT_ACTIVATION_DECLARATION` through the shared slot helpers. The body is
 * short by design - Copilot prompt files route to the public skill rather than
 * restating the whole activation contract - but "short" must not mean "silent
 * about capture capability".
 */
function renderCopilotPromptMarkdown(orchestratorAgent, agentNames) {
  const maintainerAgent = agentNames.maintainer ?? 'maintainer';
  const engineerAgent = agentNames.engineer ?? 'engineer';
  const body = fillUnsupportedActivationSlots([
    emptyAdapterSlot('activation_capability'),
    '',
    `Activate Agentic Loop for this repository with the Copilot custom agent \`${orchestratorAgent}\`.`,
    '',
    'Read `.agenticloop/project.md` first.',
    'Then follow `.github/skills/agenticloop/SKILL.md` as the Agentic Loop activation contract.',
    'If `setup_status` is `unconfirmed`, follow `.github/skills/agenticloop/references/skills/setup-agenticloop/reference.md` or confirm the defaults before selecting or creating the first task.',
    `Read \`${PROCESS_DOC_RELATIVE_PATH}\` and the canonical role contracts in \`agenticloop/agents/\` before implementation work starts.`,
    `Keep the active Copilot session as coordinator/orchestrator, route maintainer-owned work through the Copilot custom agent \`${maintainerAgent}\`, route engineer-owned work through the Copilot custom agent \`${engineerAgent}\`, and create or refine the durable task record before implementation.`,
    'Agentic Loop is serial by default. For every authorized multi-task unit, complete a current Parallel Opportunity Scan after decomposition and include its durable result or not-currently-eligible rescan trigger in implementation delegation. Load parallel-delegation before choosing serial or parallel execution.',
    '',
    emptyAdapterSlot('requested_input'),
  ].join('\n'), COPILOT_ACTIVATION_DECLARATION);

  return [
    '---',
    `description: ${quoteYamlScalar(AGENTIC_LOOP_OPERATION_DESCRIPTION)}`,
    `agent: ${quoteYamlScalar(orchestratorAgent)}`,
    '---',
    '',
    `<!-- ${COPILOT_GENERATED_MARKER}. Do not edit by hand. -->`,
    '',
    body,
    '',
  ].join('\n');
}

export function resolveCopilotAgentPath(outputDir, agentName) {
  return join(outputDir, '.github', 'agents', `${agentName}.agent.md`);
}

export function resolveCopilotPromptPath(outputDir) {
  return join(outputDir, COPILOT_PROMPT_RELATIVE_PATH);
}

export function resolveCopilotPublicSkillPath(outputDir) {
  return join(outputDir, COPILOT_SKILL_RELATIVE_PATH);
}

function generatedTextIncludesMarker(text) {
  return typeof text === 'string' && text.includes(COPILOT_GENERATED_MARKER);
}

function readGeneratedTextIfExists(filePath) {
  if (!existsSync(filePath)) return '';
  try {
    return readFileSync(filePath, 'utf-8');
  } catch {
    return '';
  }
}

export function listGeneratedCopilotAgentFiles(rootDir) {
  const agentsDir = join(rootDir, '.github', 'agents');
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return [];

  const files = [];
  for (const entry of readdirSync(agentsDir)) {
    if (!entry.endsWith('.agent.md')) continue;
    const fullPath = join(agentsDir, entry);
    if (!statSync(fullPath).isFile()) continue;
    if (generatedTextIncludesMarker(readGeneratedTextIfExists(fullPath))) {
      files.push(fullPath);
    }
  }

  return files.sort();
}

export function isGeneratedCopilotSkill(rootDir) {
  return generatedTextIncludesMarker(readGeneratedTextIfExists(resolveCopilotPublicSkillPath(rootDir)));
}

export function isGeneratedCopilotPrompt(rootDir) {
  return generatedTextIncludesMarker(readGeneratedTextIfExists(resolveCopilotPromptPath(rootDir)));
}

export function generatedCopilotArtifactsPresent(rootDir) {
  const present = [];
  if (listGeneratedCopilotAgentFiles(rootDir).length > 0) {
    present.push('.github/agents/');
  }
  if (isGeneratedCopilotSkill(rootDir)) {
    present.push(COPILOT_SKILL_RELATIVE_PATH);
  }
  if (isGeneratedCopilotPrompt(rootDir)) {
    present.push(COPILOT_PROMPT_RELATIVE_PATH);
  }
  return present;
}

function clearGeneratedCopilotAgents(outputDir) {
  for (const filePath of listGeneratedCopilotAgentFiles(outputDir)) {
    rmSync(filePath, { force: true });
  }
}

function writeCopilotPublicSkill(outputDir, skillEntries, skillReferenceMap, agentNames, backendEntries) {
  const skillDir = join(outputDir, '.github', 'skills', COPILOT_PUBLIC_SKILL_NAME);
  if (existsSync(skillDir)) {
    rmSync(skillDir, { recursive: true, force: true });
  }
  mkdirSync(skillDir, { recursive: true });

  const files = [];
  const skillPath = join(skillDir, 'SKILL.md');
  writeFileSync(skillPath, renderCopilotPublicSkill(skillReferenceMap, agentNames, backendEntries), 'utf-8');
  files.push(relative(outputDir, skillPath).replace(/\\/g, '/'));

  files.push(...writeCopilotSkillReferences(
    skillEntries,
    skillReferenceMap,
    join(skillDir, 'references', 'skills'),
    outputDir
  ));

  files.push(...writeCopilotBackendReferences(
    backendEntries,
    join(skillDir, 'references', 'backends'),
    outputDir,
    skillReferenceMap
  ));

  return files;
}

export function generateCopilotArtifacts(alConfig, repoRoot, outputDir) {
  const copilotAdapter = alConfig.adapters?.copilot ?? {};
  const capabilityInventory = {
    copilot: buildEffectiveHostRoleCapabilityInventory('copilot', copilotAdapter),
  };
  const roleBindings = copilotAdapter.roleBindings ?? {};
  const agentNames = Object.fromEntries(
    WORKFLOW_ROLE_IDS.map(roleName => [roleName, roleBindings[roleName]?.agent ?? roleName])
  );
  const skillEntries = readCanonicalSkillEntries(repoRoot, alConfig);
  const backendEntries = readCanonicalBackendEntries(repoRoot, alConfig);
  const relativeSkillReferenceMap = buildSkillReferenceMap(
    skillEntries,
    copilotSkillReferenceRelativePath
  );
  addBackendReferencesToMap(relativeSkillReferenceMap, backendEntries, copilotBackendReferenceRelativePath);
  const absoluteSkillReferenceMap = buildSkillReferenceMap(
    skillEntries,
    copilotSkillReferenceAbsolutePath
  );
  addBackendReferencesToMap(absoluteSkillReferenceMap, backendEntries, copilotBackendReferenceAbsolutePath);

  mkdirSync(outputDir, { recursive: true });
  clearGeneratedCopilotAgents(outputDir);

  const files = [];
  const agentsDir = join(outputDir, '.github', 'agents');
  mkdirSync(agentsDir, { recursive: true });

  for (const roleName of WORKFLOW_ROLE_IDS) {
    const agentName = agentNames[roleName] ?? roleName;
    const roleRecord = buildRoleRecord(alConfig, repoRoot, roleName);
    const modelSettings = resolveRoleModel(alConfig, 'copilot', roleName, copilotAdapter);
    const md = renderCopilotAgentMarkdown(
      agentName,
      roleName,
      roleRecord,
      modelSettings,
      absoluteSkillReferenceMap,
      agentNames,
      capabilityInventory
    );
    const mdPath = resolveCopilotAgentPath(outputDir, agentName);
    mkdirSync(dirname(mdPath), { recursive: true });
    writeFileSync(mdPath, md, 'utf-8');
    files.push(relative(outputDir, mdPath).replace(/\\/g, '/'));
  }

  files.push(...writeCopilotPublicSkill(
    outputDir,
    skillEntries,
    relativeSkillReferenceMap,
    agentNames,
    backendEntries
  ));

  const promptPath = resolveCopilotPromptPath(outputDir);
  mkdirSync(dirname(promptPath), { recursive: true });
  writeFileSync(
    promptPath,
    renderCopilotPromptMarkdown(agentNames.orchestrator ?? 'orchestrator', agentNames),
    'utf-8'
  );
  files.push(relative(outputDir, promptPath).replace(/\\/g, '/'));
  const sidecarRelPath = hostRoleCapabilitySidecarRelativePath('copilot');
  const sidecarPath = join(outputDir, sidecarRelPath);
  mkdirSync(dirname(sidecarPath), { recursive: true });
  writeFileSync(sidecarPath, renderHostRoleCapabilitySidecar('copilot', copilotAdapter), 'utf-8');
  files.push(sidecarRelPath);

  return { files };
}

/**
 * Plan Copilot adapter artifacts without writing to the filesystem.
 *
 * @param {object} alConfig
 * @param {string} repoRoot
 * @param {string} outputDir
 * @returns {{ actions: Array, files: string[], adapter: string }}
 */
export function planCopilotArtifacts(alConfig, repoRoot, outputDir) {
  const copilotAdapter = alConfig.adapters?.copilot ?? {};
  const capabilityInventory = {
    copilot: buildEffectiveHostRoleCapabilityInventory('copilot', copilotAdapter),
  };
  const roleBindings = copilotAdapter.roleBindings ?? {};
  const agentNames = Object.fromEntries(
    WORKFLOW_ROLE_IDS.map(roleName => [roleName, roleBindings[roleName]?.agent ?? roleName])
  );
  const skillEntries = readCanonicalSkillEntries(repoRoot, alConfig);
  const backendEntries = readCanonicalBackendEntries(repoRoot, alConfig);
  const relativeSkillReferenceMap = buildSkillReferenceMap(
    skillEntries, copilotSkillReferenceRelativePath
  );
  addBackendReferencesToMap(relativeSkillReferenceMap, backendEntries, copilotBackendReferenceRelativePath);
  const absoluteSkillReferenceMap = buildSkillReferenceMap(
    skillEntries, copilotSkillReferenceAbsolutePath
  );
  addBackendReferencesToMap(absoluteSkillReferenceMap, backendEntries, copilotBackendReferenceAbsolutePath);

  const actions = [];
  const files = [];

  actions.push({ type: 'clear-owned-directory', adapter: 'copilot', relPath: '.github/agents' });
  actions.push({ type: 'clear-owned-directory', adapter: 'copilot', relPath: '.github/prompts' });

  // .github/agents/<name>.agent.md
  for (const roleName of WORKFLOW_ROLE_IDS) {
    const agentName = agentNames[roleName] ?? roleName;
    const roleRecord = buildRoleRecord(alConfig, repoRoot, roleName);
    const modelSettings = resolveRoleModel(alConfig, 'copilot', roleName, copilotAdapter);
    const md = renderCopilotAgentMarkdown(
      agentName, roleName, roleRecord, modelSettings, absoluteSkillReferenceMap, agentNames,
      capabilityInventory
    );
    const relPath = `.github/agents/${agentName}.agent.md`;
    actions.push({
      type: 'write-file',
      adapter: 'copilot',
      relPath,
      content: md,
      marker: COPILOT_GENERATED_MARKER,
    });
    files.push(relPath);
  }

  // Public skill directory.
  const skillDirRelPath = `.github/skills/${COPILOT_PUBLIC_SKILL_NAME}`;
  actions.push({
    type: 'clear-owned-directory',
    adapter: 'copilot',
    relPath: skillDirRelPath,
  });

  // SKILL.md
  actions.push({
    type: 'write-file',
    adapter: 'copilot',
    relPath: `${skillDirRelPath}/SKILL.md`,
    content: renderCopilotPublicSkill(relativeSkillReferenceMap, agentNames, backendEntries),
    marker: COPILOT_GENERATED_MARKER,
  });
  files.push(`${skillDirRelPath}/SKILL.md`);

  // Skill reference trees.
  for (const entry of skillEntries) {
    const refActions = planReferenceTree(
      entry.sourceDir,
      `${skillDirRelPath}/references/skills/${entry.canonicalName}`,
      'copilot',
      (content) => renderReferenceMarkdown(content, relativeSkillReferenceMap),
      COPILOT_GENERATED_MARKER
    );
    actions.push(...refActions);
    files.push(...refActions.map(a => a.relPath));
  }

  // Backend references.
  for (const entry of backendEntries) {
    const relPath = `${skillDirRelPath}/references/backends/${entry.filename}`;
    const content = renderCopilotGeneratedText(
      readFileSync(entry.sourceFile, 'utf-8'), relativeSkillReferenceMap
    );
    actions.push({ type: 'write-file', adapter: 'copilot', relPath, content });
    files.push(relPath);
  }

  // Prompt file.
  actions.push({
    type: 'write-file',
    adapter: 'copilot',
    relPath: COPILOT_PROMPT_RELATIVE_PATH,
    content: renderCopilotPromptMarkdown(agentNames.orchestrator ?? 'orchestrator', agentNames),
    marker: COPILOT_GENERATED_MARKER,
  });
  files.push(COPILOT_PROMPT_RELATIVE_PATH);
  const sidecarRelPath = hostRoleCapabilitySidecarRelativePath('copilot');
  actions.push({
    type: 'write-file',
    adapter: 'copilot',
    relPath: sidecarRelPath,
    content: renderHostRoleCapabilitySidecar('copilot', copilotAdapter),
  });
  files.push(sidecarRelPath);

  return { actions, files, adapter: 'copilot' };
}
