/**
 * Cursor host adapter.
 *
 * Status: experimental.
 *
 * Repo-local Cursor MVP support focuses on explicit activation plus one public
 * Agentic Loop skill surface:
 *   - Custom subagents under .cursor/agents/*.md.
 *   - One public .cursor/skills/agenticloop/SKILL.md skill.
 *   - Internal procedure references under
 *     .cursor/skills/agenticloop/references/.
 *
 * This MVP intentionally does NOT generate .cursor/rules/ or any always-on
 * hooks. Agentic Loop stays explicit-activation only: invoke /agenticloop in
 * Cursor Agent chat when you want the workflow.
 */

import {
  copyFileSync,
  existsSync,
  mkdirSync,
  readFileSync,
  readdirSync,
  rmSync,
  statSync,
  writeFileSync,
} from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { fileURLToPath } from 'node:url';
import { parseFrontmatter } from '../frontmatter.js';
import { assertSharedAgenticLoopPluginCompatibility } from '../adapter-plugin-compatibility.js';
import {
  BACKENDS_SOURCE_DIRECTORY,
  PROCESS_DOC_RELATIVE_PATH,
  bundledToolkitPath,
} from '../layout.js';
import {
  AGENTIC_LOOP_OPERATION_DESCRIPTION,
  buildRoleRecord,
  readCanonicalSkillEntries,
  resolveRoleModel,
} from './shared.js';

const CURSOR_START_COMMAND = bundledToolkitPath('agenticloop/commands/start.md');
const PACKAGE_JSON_PATH = fileURLToPath(
  new URL('../../package.json', import.meta.url)
);

export const CURSOR_PUBLIC_SKILL_NAME = 'agenticloop';
export const CURSOR_GENERATED_MARKER = 'Generated by: agenticloop generate cursor';
export const CURSOR_SKILL_RELATIVE_PATH =
  `.cursor/skills/${CURSOR_PUBLIC_SKILL_NAME}/SKILL.md`;
export const CURSOR_PLUGIN_MANIFEST_RELATIVE_PATH =
  'plugins/agenticloop/.cursor-plugin/plugin.json';
export const CURSOR_REQUIRED_PUBLIC_REFERENCES = [
  'role-delegation',
  'task-record-contract',
  'setup-agenticloop',
  'blocked-state',
];

function quoteYamlScalar(value) {
  return JSON.stringify(String(value));
}

function capitalize(value) {
  return value ? value[0].toUpperCase() + value.slice(1) : '';
}

function replaceAll(value, search, replacement) {
  return value.split(search).join(replacement);
}

function cursorSkillReferenceRelativePath(canonicalName) {
  return `references/skills/${canonicalName}/reference.md`;
}

function cursorSkillReferenceAbsolutePath(canonicalName) {
  return `.cursor/skills/${CURSOR_PUBLIC_SKILL_NAME}/references/skills/${canonicalName}/reference.md`;
}

function cursorPluginSkillReferenceAbsolutePath(canonicalName) {
  return `plugins/agenticloop/skills/${CURSOR_PUBLIC_SKILL_NAME}/references/skills/${canonicalName}/reference.md`;
}

function cursorBackendReferenceRelativePath(filename) {
  return `references/backends/${filename}`;
}

function cursorBackendReferenceAbsolutePath(filename) {
  return `.cursor/skills/${CURSOR_PUBLIC_SKILL_NAME}/references/backends/${filename}`;
}

function cursorPluginBackendReferenceAbsolutePath(filename) {
  return `plugins/agenticloop/skills/${CURSOR_PUBLIC_SKILL_NAME}/references/backends/${filename}`;
}

function buildSkillReferenceMap(entries, pathBuilder) {
  const map = new Map();
  for (const entry of entries) {
    map.set(entry.canonicalName, pathBuilder(entry.canonicalName));
  }
  return map;
}

function addBackendReferencesToMap(map, backendEntries, pathBuilder) {
  for (const entry of backendEntries) {
    map.set(`backends/${entry.filename}`, pathBuilder(entry.filename));
    map.set(`agenticloop/backends/${entry.filename}`, pathBuilder(entry.filename));
  }
}

function skillReferencePath(skillReferenceMap, canonicalName, pathBuilder) {
  return skillReferenceMap.get(canonicalName) ?? pathBuilder(canonicalName);
}

function rewriteCursorSkillReferences(text, skillReferenceMap) {
  let rewritten = text.replace(/\[\[([A-Za-z0-9_.-]+)\]\]/g, (full, name) => {
    const mapped = skillReferenceMap.get(name);
    return mapped ? `\`${mapped}\`` : full;
  });

  for (const [canonicalName, mappedPath] of skillReferenceMap.entries()) {
    rewritten = replaceAll(rewritten, `\`${canonicalName}\``, `\`${mappedPath}\``);
    rewritten = replaceAll(
      rewritten,
      `\`skills/${canonicalName}/SKILL.md\``,
      `\`${mappedPath}\``
    );
    rewritten = replaceAll(
      rewritten,
      `\`agenticloop/skills/${canonicalName}/SKILL.md\``,
      `\`${mappedPath}\``
    );
  }

  return rewritten;
}

function renderCursorGeneratedText(text, skillReferenceMap) {
  return rewriteCursorSkillReferences(text, skillReferenceMap);
}

function renderReferenceMarkdown(sourceText, skillReferenceMap) {
  return renderCursorGeneratedText(sourceText, skillReferenceMap);
}

function readCanonicalBackendEntries(repoRoot, alConfig) {
  const backendsSrc = alConfig.backends?.sourceDirectory ?? BACKENDS_SOURCE_DIRECTORY;
  const srcDir = join(repoRoot, backendsSrc);
  if (!existsSync(srcDir)) return [];

  const entries = [];
  for (const entry of readdirSync(srcDir)) {
    if (!entry.endsWith('.md')) continue;
    const sourceFile = join(srcDir, entry);
    if (!statSync(sourceFile).isFile()) continue;
    entries.push({ filename: entry, sourceFile });
  }

  return entries.sort((a, b) => a.filename.localeCompare(b.filename));
}

function copyCursorReferenceTree(
  sourceDir,
  destDir,
  outputDir,
  skillReferenceMap,
  copied,
  currentSrc = sourceDir,
  currentDest = destDir
) {
  mkdirSync(currentDest, { recursive: true });

  for (const entry of readdirSync(currentSrc)) {
    const sourceEntry = join(currentSrc, entry);
    const entryStat = statSync(sourceEntry);

    if (entryStat.isDirectory()) {
      copyCursorReferenceTree(
        sourceDir,
        destDir,
        outputDir,
        skillReferenceMap,
        copied,
        sourceEntry,
        join(currentDest, entry)
      );
      continue;
    }

    const destName = entry === 'SKILL.md' ? 'reference.md' : entry;
    const destEntry = join(currentDest, destName);

    if (entry === 'SKILL.md') {
      const rendered = renderReferenceMarkdown(
        readFileSync(sourceEntry, 'utf-8'),
        skillReferenceMap
      );
      writeFileSync(destEntry, rendered, 'utf-8');
    } else {
      copyFileSync(sourceEntry, destEntry);
    }

    copied.push(relative(outputDir, destEntry).replace(/\\/g, '/'));
  }
}

function writeCursorSkillReferences(skillEntries, skillReferenceMap, destRoot, outputDir) {
  mkdirSync(destRoot, { recursive: true });
  const copied = [];

  for (const entry of skillEntries) {
    const destDir = join(destRoot, entry.canonicalName);
    copyCursorReferenceTree(entry.sourceDir, destDir, outputDir, skillReferenceMap, copied);
  }

  return copied;
}

function writeCursorBackendReferences(backendEntries, destRoot, outputDir, skillReferenceMap) {
  mkdirSync(destRoot, { recursive: true });
  const copied = [];

  for (const entry of backendEntries) {
    const destFile = join(destRoot, entry.filename);
    const rendered = renderCursorGeneratedText(
      readFileSync(entry.sourceFile, 'utf-8'),
      skillReferenceMap
    );
    writeFileSync(destFile, rendered, 'utf-8');
    copied.push(relative(outputDir, destFile).replace(/\\/g, '/'));
  }

  return copied;
}

function loadCursorStartCommandBody() {
  const source = readFileSync(CURSOR_START_COMMAND, 'utf-8');
  const [, body] = parseFrontmatter(source);
  return body.trim();
}

function replaceRequiredTemplateText(text, search, replacement, label) {
  if (!text.includes(search)) {
    throw new Error(
      `Cursor start command template drift: expected ${label} text in commands/start.md`
    );
  }
  return text.replace(search, replacement);
}

function buildCursorInternalReferenceIndexLines(skillReferenceMap, backendEntries) {
  const lines = ['Internal Agentic Loop references:'];
  for (const skillName of CURSOR_REQUIRED_PUBLIC_REFERENCES) {
    lines.push(
      `- ${skillName}: \`${skillReferencePath(skillReferenceMap, skillName, cursorSkillReferenceRelativePath)}\``
    );
  }
  for (const entry of backendEntries) {
    const name = entry.filename === 'README.md'
      ? 'backend/index'
      : `backend/${entry.filename.replace(/\.md$/, '')}`;
    lines.push(`- ${name}: \`${cursorBackendReferenceRelativePath(entry.filename)}\``);
  }
  return lines;
}

function renderCursorPublicSkill(skillReferenceMap, agentNames, backendEntries, options = {}) {
  const setupReferencePath = skillReferencePath(
    skillReferenceMap,
    'setup-agenticloop',
    cursorSkillReferenceRelativePath
  );
  const roleDelegationReferencePath = skillReferencePath(
    skillReferenceMap,
    'role-delegation',
    cursorSkillReferenceRelativePath
  );
  const blockedStateReferencePath = skillReferencePath(
    skillReferenceMap,
    'blocked-state',
    cursorSkillReferenceRelativePath
  );
  const maintainerAgent = agentNames.maintainer ?? 'maintainer';
  const engineerAgent = agentNames.engineer ?? 'engineer';
  const agentRootDisplay = options.agentRootDisplay ?? '.cursor/agents';
  let body = loadCursorStartCommandBody();

  body = replaceRequiredTemplateText(
    body,
    'route `agenticloop/skills/setup-agenticloop/SKILL.md` or confirm the defaults before\nselecting or creating the first task.',
    `route \`${setupReferencePath}\` or confirm the defaults before selecting or creating the first task.`,
    'setup routing'
  );

  body = replaceRequiredTemplateText(
    body,
    'Keep the main session as the coordinator: it reads the selected project config\nand process docs, routes task authoring, review, acceptance, and closeout\nthrough the maintainer role, routes scoped implementation and revision work\nthrough the engineer role, and should not directly edit implementation files\nunless the human explicitly asks. Respect the Advance Authorization Boundary,\nblocked-state handling, decision records, event logging rules, and configured\ngroup approval gates.',
    `Keep the active Cursor session as the coordinator/orchestrator. It reads the selected project config
and process docs, routes task authoring, review, acceptance, and closeout
through the Cursor subagent \`${maintainerAgent}\` from \`${agentRootDisplay}/${maintainerAgent}.md\`, routes scoped implementation and revision work
through the Cursor subagent \`${engineerAgent}\` from \`${agentRootDisplay}/${engineerAgent}.md\`, and should keep coordinator edits bounded to setup confirmation,
task-record refinement, review, or closeout unless the human explicitly asks for direct implementation work.

Use real Cursor subagent delegation where the current surface supports it. If delegation is unavailable after a capability check, record a bounded fallback reason and continue according to \`${roleDelegationReferencePath}\`.

Follow \`${roleDelegationReferencePath}\` for delegation capability checks, backend enforcement, bounded fallback, and \`role.invoked\` event logging. Respect the Advance Authorization Boundary, \`${blockedStateReferencePath}\`, decision records, event logging rules, and configured group approval gates.`,
    'coordinator delegation'
  );

  body = replaceRequiredTemplateText(
    body,
    'Requested task or context: `$ARGUMENTS`',
    'Requested task or context: use the current user request or selected task id as the work unit to coordinate.',
    'argument placeholder'
  );

  body = renderCursorGeneratedText(body, skillReferenceMap);

  const description =
    `Explicit /agenticloop activation for Cursor: ${AGENTIC_LOOP_OPERATION_DESCRIPTION}`;

  return [
    '---',
    `name: ${quoteYamlScalar(CURSOR_PUBLIC_SKILL_NAME)}`,
    `description: ${quoteYamlScalar(description)}`,
    'disable-model-invocation: true',
    '---',
    '',
    `<!-- ${CURSOR_GENERATED_MARKER}. Do not edit by hand. -->`,
    '',
    body,
    '',
    ...buildCursorInternalReferenceIndexLines(skillReferenceMap, backendEntries),
    '',
  ].join('\n');
}

function formatRequiredSkillLines(requiredSkills, skillReferenceMap, pathBuilder) {
  return (requiredSkills ?? []).map(skillName => {
    const referencePath = skillReferencePath(
      skillReferenceMap,
      skillName,
      pathBuilder
    );
    return `- \`${skillName}\`: \`${referencePath}\``;
  });
}

function buildCursorAgentBody(
  roleName,
  roleSourceFile,
  requiredSkills,
  roleBody,
  skillReferenceMap,
  agentNames,
  backendEntries,
  backendPathBuilder,
  skillPathBuilder
) {
  const maintainerAgent = agentNames.maintainer ?? 'maintainer';
  const engineerAgent = agentNames.engineer ?? 'engineer';
  const roleDelegationReferencePath = skillReferencePath(
    skillReferenceMap,
    'role-delegation',
    skillPathBuilder
  );
  const lines = [];
  lines.push(`You are the Agentic Loop ${capitalize(roleName)} subagent for the target project in Cursor.`);
  lines.push(`Canonical role source: \`${roleSourceFile}\`.`);
  lines.push('Read `.agenticloop/project.md` before acting for setup status, task backend, document selections, naming, grouping, and event logging.');
  lines.push(`Follow \`${PROCESS_DOC_RELATIVE_PATH}\` as the workflow methodology.`);
  lines.push('Path convention: toolkit source (agents/, skills/, backends/) lives under agenticloop/ (no leading dot); target project state (project.md, tasks/, decisions/, improvements/) lives under .agenticloop/ (leading dot). .agenticloop/agents, .agenticloop/skills, and .agenticloop/backends are invalid paths.');

  const skillLines = formatRequiredSkillLines(requiredSkills, skillReferenceMap, skillPathBuilder);
  if (skillLines.length > 0) {
    lines.push('Agentic Loop internal references to use when their trigger applies:');
    lines.push(...skillLines);
  }

  if (backendEntries.length > 0) {
    lines.push('Backend projection references:');
    for (const entry of backendEntries) {
      lines.push(`- \`${backendPathBuilder(entry.filename)}\``);
    }
  }

  if (roleName === 'orchestrator') {
    lines.push(`The active Cursor session is the coordinator/orchestrator. When maintainer-owned work is needed, delegate through the Cursor subagent \`${maintainerAgent}\`. When engineer-owned work is needed, delegate through the Cursor subagent \`${engineerAgent}\` instead of doing that work inline.`);
    lines.push('Agentic Loop is serial by default. Do not start parallel Cursor subagents unless a recorded concurrency plan, lease, and join condition prove the lanes do not collide.');
    lines.push('For authorized multi-task units, perform a Parallel Opportunity Scan before choosing serial execution. If 2+ ready tasks are independent and collision criteria are known/disjoint, prefer a bounded parallel batch of up to 3 lanes; otherwise record the concrete serial reason.');
    lines.push('Use real Cursor subagent delegation where the current surface supports it.');
    lines.push(`If delegation is unavailable after a capability check, record a bounded fallback reason and continue according to \`${roleDelegationReferencePath}\`.`);
    lines.push('For long-running or parallel delegated work, include the lease with an observable-step checkpoint cadence and require a status return at the progress checkpoint, stop condition, wrong branch/worktree, or no-progress budget.');
    lines.push('When event logging is enabled, emit `role.invoked` after a real role invocation or explicit fallback role assumption.');
    lines.push('Do not directly edit implementation files unless the human explicitly asks, and keep any coordinator-side edits bounded to setup confirmation, task-record refinement, review, or closeout.');
  } else if (roleName === 'maintainer') {
    lines.push('Stay within maintainer boundaries: own setup confirmation, task records, review, acceptance, follow-up triage, and closeout.');
    lines.push('Honor any delegation lease from the orchestrator, including any observable-step checkpoint cadence, and return status when the lease, stop condition, collision, or no-progress budget requires it.');
    lines.push('Do not implement code changes. Stop and hand control back after producing maintainer-owned output for the orchestrator or human.');
  } else if (roleName === 'engineer') {
    lines.push('Stay within engineer boundaries: implement only the scoped task-record work, run checks, and publish fresh evidence.');
    lines.push('Honor any delegation lease from the orchestrator, including any observable-step checkpoint cadence, and return status when the lease, stop condition, wrong branch/worktree, collision, or no-progress budget requires it.');
    lines.push('Do not accept tasks or perform final maintainer review. Stop and hand control back once implementation evidence is ready for maintainer review.');
  }

  lines.push('');
  lines.push('Canonical role contract follows:');
  lines.push('');
  const renderedRoleBody = renderCursorGeneratedText(roleBody, skillReferenceMap);
  if (renderedRoleBody) {
    lines.push(renderedRoleBody);
  }
  return lines.join('\n');
}

function renderCursorAgentMarkdown(
  agentName,
  roleName,
  roleRecord,
  modelSettings,
  skillReferenceMap,
  agentNames,
  backendEntries,
  backendPathBuilder,
  skillPathBuilder
) {
  const lines = [];
  const model = modelSettings.model?.trim() ? modelSettings.model.trim() : 'inherit';
  lines.push('---');
  lines.push(`name: ${quoteYamlScalar(agentName)}`);
  if (roleRecord.description) {
    lines.push(`description: ${quoteYamlScalar(roleRecord.description.replace(/\n+/g, ' '))}`);
  }
  lines.push(`model: ${quoteYamlScalar(model)}`);
  lines.push(`readonly: ${roleName === 'orchestrator' ? 'true' : 'false'}`);
  lines.push('---');
  lines.push('');
  lines.push(`<!-- ${CURSOR_GENERATED_MARKER}. Do not edit by hand. -->`);
  lines.push('');
  lines.push(buildCursorAgentBody(
    roleName,
    roleRecord.sourceFile,
    roleRecord.requiredSkills,
    roleRecord.promptBody,
    skillReferenceMap,
    agentNames,
    backendEntries,
    backendPathBuilder,
    skillPathBuilder
  ));
  lines.push('');
  return lines.join('\n');
}

function generatedTextIncludesMarker(text) {
  return typeof text === 'string' && text.includes(CURSOR_GENERATED_MARKER);
}

function readGeneratedTextIfExists(filePath) {
  if (!existsSync(filePath)) return '';
  try {
    return readFileSync(filePath, 'utf-8');
  } catch {
    return '';
  }
}

export function resolveCursorAgentPath(outputDir, agentName) {
  return join(outputDir, '.cursor', 'agents', `${agentName}.md`);
}

export function resolveCursorPublicSkillPath(outputDir) {
  return join(outputDir, CURSOR_SKILL_RELATIVE_PATH);
}

export function listGeneratedCursorAgentFiles(rootDir) {
  const agentsDir = join(rootDir, '.cursor', 'agents');
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return [];

  const files = [];
  for (const entry of readdirSync(agentsDir)) {
    if (!entry.endsWith('.md')) continue;
    const fullPath = join(agentsDir, entry);
    if (!statSync(fullPath).isFile()) continue;
    if (generatedTextIncludesMarker(readGeneratedTextIfExists(fullPath))) {
      files.push(fullPath);
    }
  }

  return files.sort();
}

export function isGeneratedCursorSkill(rootDir) {
  return generatedTextIncludesMarker(readGeneratedTextIfExists(resolveCursorPublicSkillPath(rootDir)));
}

export function generatedCursorArtifactsPresent(rootDir) {
  const present = [];
  if (listGeneratedCursorAgentFiles(rootDir).length > 0) {
    present.push('.cursor/agents/');
  }
  if (isGeneratedCursorSkill(rootDir)) {
    present.push(CURSOR_SKILL_RELATIVE_PATH);
  }
  if (existsSync(join(rootDir, 'plugins', 'agenticloop', '.cursor-plugin', 'plugin.json'))) {
    present.push(CURSOR_PLUGIN_MANIFEST_RELATIVE_PATH);
  }
  return present;
}

function clearGeneratedCursorAgents(outputDir) {
  for (const filePath of listGeneratedCursorAgentFiles(outputDir)) {
    rmSync(filePath, { force: true });
  }
}

function writeCursorAgents(
  agentsDir,
  outputDir,
  repoRoot,
  alConfig,
  cursorAdapter,
  agentNames,
  skillReferenceMap,
  backendEntries,
  backendPathBuilder,
  skillPathBuilder
) {
  mkdirSync(agentsDir, { recursive: true });
  const files = [];

  for (const roleName of Object.keys(alConfig.roles ?? {})) {
    const agentName = agentNames[roleName] ?? roleName;
    const roleRecord = buildRoleRecord(alConfig, repoRoot, roleName);
    const modelSettings = resolveRoleModel(alConfig, 'cursor', roleName, cursorAdapter);
    const md = renderCursorAgentMarkdown(
      agentName,
      roleName,
      roleRecord,
      modelSettings,
      skillReferenceMap,
      agentNames,
      backendEntries,
      backendPathBuilder,
      skillPathBuilder
    );
    const mdPath = join(agentsDir, `${agentName}.md`);
    mkdirSync(dirname(mdPath), { recursive: true });
    writeFileSync(mdPath, md, 'utf-8');
    files.push(relative(outputDir, mdPath).replace(/\\/g, '/'));
  }

  return files;
}

function writeCursorPublicSkillSurface(
  skillsRoot,
  outputDir,
  skillEntries,
  skillReferenceMap,
  agentNames,
  backendEntries,
  options = {}
) {
  const skillDir = join(skillsRoot, CURSOR_PUBLIC_SKILL_NAME);
  if (existsSync(skillDir)) {
    rmSync(skillDir, { recursive: true, force: true });
  }
  mkdirSync(skillDir, { recursive: true });

  const files = [];
  const skillPath = join(skillDir, 'SKILL.md');
  writeFileSync(
    skillPath,
    renderCursorPublicSkill(skillReferenceMap, agentNames, backendEntries, options),
    'utf-8'
  );
  files.push(relative(outputDir, skillPath).replace(/\\/g, '/'));

  files.push(...writeCursorSkillReferences(
    skillEntries,
    skillReferenceMap,
    join(skillDir, 'references', 'skills'),
    outputDir
  ));

  files.push(...writeCursorBackendReferences(
    backendEntries,
    join(skillDir, 'references', 'backends'),
    outputDir,
    skillReferenceMap
  ));

  return files;
}

function loadPackageVersion() {
  const pkg = JSON.parse(readFileSync(PACKAGE_JSON_PATH, 'utf-8'));
  return typeof pkg.version === 'string' && pkg.version.trim() ? pkg.version.trim() : '0.1.0';
}

function buildCursorPluginManifest(version) {
  return {
    name: 'agenticloop',
    version,
    description: 'Agentic Loop workflow toolkit (Cursor plugin distribution, experimental)',
    skills: './skills/',
    agents: './agents/',
  };
}

function writeOptionalCursorPluginDistribution(
  outputDir,
  repoRoot,
  alConfig,
  cursorAdapter,
  skillEntries,
  relativeSkillReferenceMap,
  pluginAbsoluteSkillReferenceMap,
  agentNames,
  backendEntries,
  version
) {
  assertSharedAgenticLoopPluginCompatibility(alConfig);

  const files = [];
  const pluginRoot = join(outputDir, 'plugins', 'agenticloop');
  const pluginCursorPluginDir = join(pluginRoot, '.cursor-plugin');
  const pluginCodexPluginDir = join(pluginRoot, '.codex-plugin');
  const pluginAgentsDir = join(pluginRoot, 'agents');
  const pluginSkillDir = join(pluginRoot, 'skills', CURSOR_PUBLIC_SKILL_NAME);

  rmSync(pluginCursorPluginDir, { recursive: true, force: true });
  rmSync(pluginCodexPluginDir, { recursive: true, force: true });
  rmSync(pluginAgentsDir, { recursive: true, force: true });
  rmSync(pluginSkillDir, { recursive: true, force: true });

  mkdirSync(pluginCursorPluginDir, { recursive: true });
  const pluginManifestPath = join(pluginCursorPluginDir, 'plugin.json');
  writeFileSync(
    pluginManifestPath,
    JSON.stringify(buildCursorPluginManifest(version), null, 2) + '\n',
    'utf-8'
  );
  files.push(relative(outputDir, pluginManifestPath).replace(/\\/g, '/'));

  files.push(...writeCursorAgents(
    pluginAgentsDir,
    outputDir,
    repoRoot,
    alConfig,
    cursorAdapter,
    agentNames,
    pluginAbsoluteSkillReferenceMap,
    backendEntries,
    cursorPluginBackendReferenceAbsolutePath,
    cursorPluginSkillReferenceAbsolutePath
  ));

  files.push(...writeCursorPublicSkillSurface(
    join(pluginRoot, 'skills'),
    outputDir,
    skillEntries,
    relativeSkillReferenceMap,
    agentNames,
    backendEntries,
    { agentRootDisplay: 'plugins/agenticloop/agents' }
  ));

  return files;
}

export function generateCursorArtifacts(alConfig, repoRoot, outputDir) {
  assertSharedAgenticLoopPluginCompatibility(alConfig);

  const cursorAdapter = alConfig.adapters?.cursor ?? {};
  const roleBindings = cursorAdapter.roleBindings ?? {};
  const agentNames = Object.fromEntries(
    Object.keys(alConfig.roles ?? {}).map(roleName => [roleName, roleBindings[roleName]?.agent ?? roleName])
  );
  const skillEntries = readCanonicalSkillEntries(repoRoot, alConfig);
  const backendEntries = readCanonicalBackendEntries(repoRoot, alConfig);
  const relativeSkillReferenceMap = buildSkillReferenceMap(
    skillEntries,
    cursorSkillReferenceRelativePath
  );
  addBackendReferencesToMap(relativeSkillReferenceMap, backendEntries, cursorBackendReferenceRelativePath);
  const absoluteSkillReferenceMap = buildSkillReferenceMap(
    skillEntries,
    cursorSkillReferenceAbsolutePath
  );
  addBackendReferencesToMap(absoluteSkillReferenceMap, backendEntries, cursorBackendReferenceAbsolutePath);
  const pluginAbsoluteSkillReferenceMap = buildSkillReferenceMap(
    skillEntries,
    cursorPluginSkillReferenceAbsolutePath
  );
  addBackendReferencesToMap(
    pluginAbsoluteSkillReferenceMap,
    backendEntries,
    cursorPluginBackendReferenceAbsolutePath
  );

  mkdirSync(outputDir, { recursive: true });
  clearGeneratedCursorAgents(outputDir);

  const files = [];
  files.push(...writeCursorAgents(
    join(outputDir, '.cursor', 'agents'),
    outputDir,
    repoRoot,
    alConfig,
    cursorAdapter,
    agentNames,
    absoluteSkillReferenceMap,
    backendEntries,
    cursorBackendReferenceAbsolutePath,
    cursorSkillReferenceAbsolutePath
  ));

  files.push(...writeCursorPublicSkillSurface(
    join(outputDir, '.cursor', 'skills'),
    outputDir,
    skillEntries,
    relativeSkillReferenceMap,
    agentNames,
    backendEntries,
    { agentRootDisplay: '.cursor/agents' }
  ));

  if (cursorAdapter.plugin?.enabled === true) {
    files.push(...writeOptionalCursorPluginDistribution(
      outputDir,
      repoRoot,
      alConfig,
      cursorAdapter,
      skillEntries,
      relativeSkillReferenceMap,
      pluginAbsoluteSkillReferenceMap,
      agentNames,
      backendEntries,
      loadPackageVersion()
    ));
  }

  return { files };
}
