/**
 * OpenCode host adapter.
 *
 * Generates OpenCode-native markdown agents and a repo-local command from
 * canonical Agentic Loop sources:
 *   - role files under agents/
 *   - skill references under skills/
 *   - adapter-local model settings under adapters.opencode.roleSettings
 */

import { mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, relative } from 'node:path';
import { parseFrontmatter } from '../frontmatter.js';
import {
  PROCESS_DOC_RELATIVE_PATH,
  SKILLS_SOURCE_DIRECTORY,
  bundledToolkitPath,
} from '../layout.js';
import {
  AGENTIC_LOOP_OPERATION_DESCRIPTION,
  resolveRoleModel,
  buildRoleRecord,
} from './shared.js';

export const OPENCODE_ROLE_NAMES = Object.freeze(['orchestrator', 'maintainer', 'engineer']);
export const OPENCODE_AGENT_RELATIVE_PATHS = Object.freeze({
  orchestrator: '.opencode/agents/orchestrator.md',
  maintainer: '.opencode/agents/maintainer.md',
  engineer: '.opencode/agents/engineer.md',
});
export const OPENCODE_COMMAND_RELATIVE_PATH = '.opencode/commands/agenticloop.md';

const OPENCODE_START_COMMAND = bundledToolkitPath('agenticloop/commands/start.md');

function capitalize(str) {
  return str ? str[0].toUpperCase() + str.slice(1) : '';
}

function quoteYamlScalar(value) {
  return JSON.stringify(String(value ?? ''));
}

export function normalizeSkillsSourceDir(skillsSourceDir) {
  return (skillsSourceDir ?? SKILLS_SOURCE_DIRECTORY).replace(/\\/g, '/').replace(/\/$/, '');
}

export function rewriteOpencodeSkillReferences(text, skillsSrc) {
  if (!text) return text;
  return text.replace(/\[\[([A-Za-z0-9_.-]+)\]\]/g, (_full, name) =>
    `\`${skillsSrc}/${name}/SKILL.md\``
  );
}

function buildPrompt(roleName, roleSourceFile, requiredSkills, roleBody, skillsSourceDir) {
  const skillsSrc = normalizeSkillsSourceDir(skillsSourceDir);
  let prompt = `You are the ${capitalize(roleName)} for the target project. `;
  prompt += `Follow ${roleSourceFile} as the canonical role contract. `;
  prompt += `Follow the selected project documents from .agenticloop/project.md and ${PROCESS_DOC_RELATIVE_PATH} as the Agentic Loop methodology.`;
  prompt += ' Path convention: toolkit source (agents/, skills/, backends/) lives under agenticloop/ (no leading dot); target project state (project.md, tasks/, decisions/, improvements/) lives under .agenticloop/ (leading dot). .agenticloop/agents, .agenticloop/skills, and .agenticloop/backends are invalid paths.';
  if (roleName === 'orchestrator') {
    prompt += ' Agentic Loop is serial by default; do not start parallel role work unless a recorded concurrency plan, lease, and join condition prove the lanes do not collide.';
    prompt += ' In OpenCode, use the Task tool or explicit @maintainer / @engineer invocation when available; inline fallback is allowed only after the delegation capability check in role-delegation.';
  } else {
    prompt += ' Honor any delegation lease from the orchestrator, including any observable-step checkpoint cadence, and return status when the lease, stop condition, wrong branch/worktree, or no-progress budget requires it.';
  }
  const skillLines = (requiredSkills ?? []).map(
    skillName => `- ${skillName}: ${skillsSrc}/${skillName}/SKILL.md`
  );
  if (skillLines.length > 0) {
    prompt += '\n\nAgentic Loop internal procedures: when a trigger applies, read and follow the corresponding canonical file before acting. These are file paths to open with your file-reading tool, not host skills -- do not call the host Skill tool for them, it will not find them:';
    prompt += `\n${skillLines.join('\n')}`;
  }
  if (roleBody) {
    prompt += `\n\n${rewriteOpencodeSkillReferences(roleBody, skillsSrc)}`;
  }
  return prompt;
}

export function adapterAgentName(_adapterCfg, roleName) {
  return roleName;
}

export function resolveOpencodeAgentPath(outputDir, roleName) {
  const relPath = OPENCODE_AGENT_RELATIVE_PATHS[roleName];
  if (!relPath) {
    throw new Error(`Unknown OpenCode role '${roleName}'`);
  }
  return join(outputDir, relPath);
}

export function resolveOpencodeCommandPath(outputDir) {
  return join(outputDir, OPENCODE_COMMAND_RELATIVE_PATH);
}

export function loadOpencodeCommandBody() {
  const source = readFileSync(OPENCODE_START_COMMAND, 'utf-8');
  const [, body] = parseFrontmatter(source);
  return body.trim();
}

export const GENERATED_BANNER =
  '<!-- Generated by Agentic Loop. Do not edit by hand. Source: agenticloop.json (adapters.opencode.roleSettings). Refresh: agenticloop update --adapter opencode -->';

export function renderOpencodeCommandMarkdown() {
  const body = loadOpencodeCommandBody();
  return [
    '---',
    `description: ${quoteYamlScalar(AGENTIC_LOOP_OPERATION_DESCRIPTION)}`,
    'agent: orchestrator',
    '---',
    '',
    GENERATED_BANNER,
    '',
    body,
    '',
  ].join('\n');
}

function buildOpencodeAgentRecord(alConfig, repoRoot, roleName) {
  const ocAdapter = alConfig.adapters?.opencode ?? {};
  const skillsSourceDir = alConfig.skills?.sourceDirectory ?? SKILLS_SOURCE_DIRECTORY;
  const { model, variant } = resolveRoleModel(alConfig, 'opencode', roleName, ocAdapter);
  const { description, sourceFile, promptBody, requiredSkills } =
    buildRoleRecord(alConfig, repoRoot, roleName);

  return {
    name: adapterAgentName(ocAdapter, roleName),
    description,
    sourceFile,
    requiredSkills,
    promptBody,
    mode: roleName === 'orchestrator' ? 'primary' : 'subagent',
    model,
    variant,
    prompt: buildPrompt(roleName, sourceFile, requiredSkills, promptBody, skillsSourceDir),
  };
}

export function generateOpencodeAgentRecords(alConfig, repoRoot) {
  return Object.fromEntries(
    OPENCODE_ROLE_NAMES.map(roleName => [roleName, buildOpencodeAgentRecord(alConfig, repoRoot, roleName)])
  );
}

export function renderOpencodeAgentMarkdown(agentRecord, roleName) {
  const lines = [
    '---',
    `description: ${quoteYamlScalar(agentRecord.description)}`,
    `mode: ${quoteYamlScalar(agentRecord.mode)}`,
    `model: ${quoteYamlScalar(agentRecord.model)}`,
  ];

  if (agentRecord.variant !== undefined && agentRecord.variant !== null) {
    lines.push(`variant: ${quoteYamlScalar(agentRecord.variant)}`);
  }

  if (roleName === 'orchestrator') {
    lines.push('permission:');
    lines.push('  edit: deny');
    lines.push('  task:');
    lines.push('    "*": deny');
    lines.push('    maintainer: allow');
    lines.push('    engineer: allow');
  }

  lines.push('---');
  lines.push('');
  lines.push(GENERATED_BANNER);
  lines.push('');
  lines.push(agentRecord.prompt);
  lines.push('');
  return lines.join('\n');
}

export function generateOpencodeArtifacts(alConfig, repoRoot, outputDir) {
  mkdirSync(outputDir, { recursive: true });
  const files = [];
  const records = generateOpencodeAgentRecords(alConfig, repoRoot);

  for (const roleName of OPENCODE_ROLE_NAMES) {
    const filePath = resolveOpencodeAgentPath(outputDir, roleName);
    mkdirSync(dirname(filePath), { recursive: true });
    writeFileSync(filePath, renderOpencodeAgentMarkdown(records[roleName], roleName), 'utf-8');
    files.push(relative(outputDir, filePath).replace(/\\/g, '/'));
  }

  const commandPath = resolveOpencodeCommandPath(outputDir);
  mkdirSync(dirname(commandPath), { recursive: true });
  writeFileSync(commandPath, renderOpencodeCommandMarkdown(), 'utf-8');
  files.push(relative(outputDir, commandPath).replace(/\\/g, '/'));

  return { files };
}
