/**
 * Remove Agentic Loop overlay files from a target directory.
 *
 * Manifest-first reconciliation: when a manifest exists, only exact owned
 * artifacts are removed; modified, unowned, and malformed artifacts are
 * preserved. When no manifest exists, conservative marker-based recognition
 * is used as a legacy fallback.
 *
 * Target-owned .agenticloop/ state is preserved by default.
 */

import { existsSync, mkdirSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, relative, resolve, sep } from 'node:path';
import { randomUUID } from 'node:crypto';
import {
  INSTALLED_TOOLKIT_ROOT_DIRECTORY,
  TARGET_STATE_DIRECTORY,
  isPackageSourceRepositoryRoot,
} from './layout.js';
import { inspectLegacyCanonicalAssets } from './layout-migration.js';
import {
  loadManifest,
  hashFile,
  resolveManagedPath,
  saveManifest,
} from './generated-artifacts.js';
import { computeGuidanceRemoval } from './guidance.js';
import {
  OPENCODE_ROLE_NAMES,
  OPENCODE_AGENT_RELATIVE_PATHS,
  OPENCODE_COMMAND_RELATIVE_PATH,
  GENERATED_BANNER as OPENCODE_GENERATED_BANNER,
} from './adapters/opencode.js';
import {
  isGeneratedCopilotPrompt,
  isGeneratedCopilotSkill,
  listGeneratedCopilotAgentFiles,
  resolveCopilotPromptPath,
  resolveCopilotPublicSkillPath,
} from './adapters/copilot.js';
import {
  isGeneratedCursorSkill,
  listGeneratedCursorAgentFiles,
  resolveCursorPublicSkillPath,
} from './adapters/cursor.js';

const DEFAULT_REMOVABLE_PATHS = [
  INSTALLED_TOOLKIT_ROOT_DIRECTORY,
  'agenticloop.json',
  'plugins/agenticloop',
];

const CODEX_PUBLIC_SKILL_NAME = 'agenticloop';
const CODEX_SKILL_PREFIX = 'agenticloop-';
const CODEX_GENERATED_MARKER = 'Generated by: agenticloop generate codex';
const GENERATED_CODEX_MARKETPLACE_NAME = 'agenticloop-local';
const GENERATED_LEGACY_CODEX_SKILL_NAMES = new Set([
  'agenticloop-start',
  'agenticloop-blocked-state',
  'agenticloop-change-request-gate',
  'agenticloop-debugging-before-fixes',
  'agenticloop-decision-capture',
  'agenticloop-frontend-design-quality',
  'agenticloop-github-attribution',
  'agenticloop-loop-retrospective',
  'agenticloop-ponytail',
  'agenticloop-review-and-accept',
  'agenticloop-role-delegation',
  'agenticloop-setup-agenticloop',
  'agenticloop-task-closeout',
  'agenticloop-task-record-contract',
  'agenticloop-tdd-implementation',
  'agenticloop-verification-evidence',
]);

function toDisplayPath(relPath) {
  return relPath.replace(/\\/g, '/');
}

function isPlainObject(value) {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

function assertInsideTarget(targetRoot, fullPath) {
  const resolved = resolve(fullPath);
  if (resolved !== targetRoot && !resolved.startsWith(`${targetRoot}${sep}`)) {
    throw new Error(`Refusing to remove path outside target: ${resolved}`);
  }
}

function isEmptyDir(path) {
  return existsSync(path) && statSync(path).isDirectory() && readdirSync(path).length === 0;
}

function removeEmptyParents(targetRoot, startDir, removed, dryRun) {
  let current = startDir;
  while (current !== targetRoot && current.startsWith(`${targetRoot}${sep}`)) {
    if (!isEmptyDir(current)) return;
    const rel = toDisplayPath(current.slice(targetRoot.length + 1));
    if (!dryRun) removePath(current);
    removed.push(rel);
    current = dirname(current);
  }
}

function readTextIfExists(path) {
  try {
    return existsSync(path) ? readFileSync(path, 'utf-8') : '';
  } catch {
    return '';
  }
}

function writeAtomically(path, content) {
  mkdirSync(dirname(path), { recursive: true });
  const temporary = `${path}.${randomUUID()}.tmp`;
  try { writeFileSync(temporary, content); renameSync(temporary, path); } finally { if (existsSync(temporary)) rmSync(temporary, { force: true }); }
}

function atomicWrite(path, content) {
  if (activeRemovalTransaction) activeRemovalTransaction.write(path, content);
  else writeAtomically(path, content);
}

let activeRemovalTransaction = null;

class RemovalTransaction {
  constructor(targetRoot, hooks = {}) {
    this.targetRoot = targetRoot;
    this.hooks = hooks;
    this.journal = join(targetRoot, `.agenticloop-remove-${randomUUID()}`);
    this.undo = [];
    this.state = 'active';
    this.createdAt = new Date().toISOString();
    mkdirSync(this.journal, { recursive: true });
    this.persistMetadata();
  }

  metadata(state = this.state, rollbackErrors = []) {
    return {
      schemaVersion: 1,
      state,
      createdAt: this.createdAt,
      targetRoot: this.targetRoot,
      rollbackErrors,
      operations: this.undo.map(entry => ({
        kind: entry.kind,
        originalPath: relative(this.targetRoot, entry.path).replaceAll('\\', '/'),
        ...(entry.backup ? { backup: relative(this.journal, entry.backup).replaceAll('\\', '/') } : {}),
        ...(entry.quarantine ? { quarantine: relative(this.journal, entry.quarantine).replaceAll('\\', '/') } : {}),
        ...(entry.existed !== undefined ? { existed: entry.existed } : {}),
      })),
    };
  }

  persistMetadata(state = this.state, rollbackErrors = []) {
    writeAtomically(
      join(this.journal, 'transaction.json'),
      JSON.stringify(this.metadata(state, rollbackErrors), null, 2) + '\n'
    );
  }

  missingParentDirectories(path) {
    const directories = [];
    let current = dirname(path);
    while (current !== this.targetRoot && current.startsWith(`${this.targetRoot}${sep}`)) {
      if (!existsSync(current)) directories.push(current);
      current = dirname(current);
    }
    return directories;
  }

  write(path, content) {
    this.mutateFile(path, () => writeAtomically(path, content));
  }

  mutateFile(path, mutation) {
    if (this.state !== 'active') throw new Error(`Removal transaction is ${this.state}`);
    const existed = existsSync(path);
    const bytes = existed ? readFileSync(path) : null;
    const createdDirectories = this.missingParentDirectories(path);
    const backup = existed ? join(this.journal, 'writes', `${this.undo.length}.bin`) : null;
    if (backup) {
      mkdirSync(dirname(backup), { recursive: true });
      writeFileSync(backup, bytes);
    }
    try {
      mutation();
    } catch (error) {
      for (const directory of createdDirectories) {
        try { if (isEmptyDir(directory)) rmSync(directory, { recursive: true, force: true }); } catch { /* Preserve the original mutation error. */ }
      }
      throw error;
    }
    const entry = {
      kind: 'write',
      path,
      existed,
      backup,
      undo: () => {
        if (existed) writeAtomically(path, readFileSync(backup));
        else if (existsSync(path)) rmSync(path, { recursive: true, force: true });
        for (const directory of createdDirectories) if (isEmptyDir(directory)) rmSync(directory, { recursive: true, force: true });
      },
    };
    this.undo.push(entry);
    this.persistMetadata();
  }

  remove(path) {
    if (!existsSync(path)) return;
    if (this.state !== 'active') throw new Error(`Removal transaction is ${this.state}`);
    assertInsideTarget(this.targetRoot, path);
    const quarantine = join(this.journal, 'deleted', String(this.undo.length));
    mkdirSync(dirname(quarantine), { recursive: true });
    renameSync(path, quarantine);
    const entry = {
      kind: 'quarantine',
      path,
      quarantine,
      undo: () => {
        if (existsSync(path)) rmSync(path, { recursive: true, force: true });
        mkdirSync(dirname(path), { recursive: true });
        renameSync(quarantine, path);
      },
    };
    this.undo.push(entry);
    this.persistMetadata();
    this.hooks.afterQuarantine?.(path);
  }

  rollback() {
    if (this.state === 'committed' || this.state === 'cleanup-failed') {
      return { completed: false, errors: ['rollback is not permitted after logical commit'], journalPath: existsSync(this.journal) ? this.journal : null };
    }
    this.state = 'rolling-back';
    const errors = [];
    for (const entry of [...this.undo].reverse()) try {
      entry.undo();
    } catch (error) { errors.push(`rollback ${entry.path}: ${error.message}`); }
    if (errors.length > 0) {
      this.state = 'rollback-failed';
      try { this.persistMetadata(this.state, errors); } catch (error) { errors.push(`rollback recovery metadata: ${error.message}`); }
      return { completed: false, errors, journalPath: existsSync(this.journal) ? this.journal : null };
    }
    try {
      if (existsSync(this.journal)) rmSync(this.journal, { recursive: true, force: true });
    } catch (error) {
      this.state = 'rollback-cleanup-failed';
      return { completed: true, errors: [`rollback journal cleanup: ${error.message}`], journalPath: existsSync(this.journal) ? this.journal : null };
    }
    this.state = 'rolled-back';
    return { completed: true, errors: [], journalPath: null };
  }

  markCommitted() {
    if (this.state !== 'active') throw new Error(`Removal transaction is ${this.state}`);
    this.persistMetadata('committed');
    this.state = 'committed';
  }

  abort() {
    if (this.state !== 'active') throw new Error(`Removal transaction is ${this.state}`);
    if (this.undo.length > 0) throw new Error('Cannot abort a removal transaction after mutations have started');
    this.state = 'aborted';
    try {
      if (existsSync(this.journal)) rmSync(this.journal, { recursive: true, force: true });
      return [];
    } catch (error) {
      return [`Removal transaction abort cleanup failed; journal retained at ${this.journal}: ${error.message}`];
    }
  }

  cleanupQuarantine() {
    if (this.state !== 'committed') throw new Error(`Quarantine cleanup requires a committed transaction, received ${this.state}`);
    try {
      if (this.hooks.cleanupQuarantine) this.hooks.cleanupQuarantine(this.journal, () => rmSync(this.journal, { recursive: true, force: true }));
      else if (existsSync(this.journal)) rmSync(this.journal, { recursive: true, force: true });
      return [];
    } catch (error) {
      this.state = 'cleanup-failed';
      const retained = existsSync(this.journal) ? `; quarantine journal retained at ${this.journal}` : '';
      return [`Quarantine cleanup failed after logical commit${retained}: ${error.message}`];
    }
  }
}

function removePath(path) {
  if (activeRemovalTransaction) activeRemovalTransaction.remove(path);
  else if (existsSync(path)) rmSync(path, { recursive: true, force: true });
}

// ---------------------------------------------------------------------------
// Manifest-first removal
// ---------------------------------------------------------------------------

/**
 * Remove artifacts using the ownership manifest.
 * Returns { used, retained, valid } where:
 *   used=true, valid=true   — manifest found and used successfully
 *   used=true, valid=false  — manifest malformed; removal refused
 *   used=false              — no manifest found
 */
function removeWithManifest(targetRoot, dryRun, options = {}) {
  const removed = [];
  const released = [];
  const skipped = [];
  const errors = [];
  let manifest;
  try {
    manifest = loadManifest(targetRoot);
  } catch (error) {
    errors.push(`Ownership manifest is malformed: ${error instanceof Error ? error.message : String(error)}. Refusing to remove with unsafe heuristic fallback.`);
    return { used: true, retained: [], valid: false, committed: false, removed, released, skipped, errors };
  }
  if (!manifest) return { used: false, retained: [], valid: true, committed: false, removed, released, skipped, errors };

  const retained = [];
  const writes = new Map();
  const deletes = [];
  const emptyCandidates = [];

  const pointerParts = (path) => path.slice(1).split('/').map(part => part.replace(/~1/g, '/').replace(/~0/g, '~'));
  const same = (left, right) => JSON.stringify(left) === JSON.stringify(right);

  for (const entry of manifest.entries) {
    let fullPath;
    try { fullPath = resolveManagedPath(targetRoot, entry.outputRoot, entry.relPath); } catch (error) {
      errors.push(`${entry.relPath}: ${error.message}`); retained.push(entry); continue;
    }
    if (entry.kind === 'file') {
      if (!existsSync(fullPath) || hashFile(fullPath) === entry.hash) {
        deletes.push(fullPath); emptyCandidates.push(fullPath); removed.push(entry.relPath);
      } else {
        retained.push(entry); skipped.push(`${entry.relPath} (modified since generation; preserved)`);
      }
      continue;
    }
    if (entry.kind === 'gitignore-line') {
      if (!existsSync(fullPath)) { removed.push(`${entry.relPath} (already absent)`); continue; }
      const original = writes.get(fullPath) ?? readFileSync(fullPath, 'utf8');
      const ending = original.includes('\r\n') ? '\r\n' : '\n';
      const lines = original.split(/\r?\n/);
      const matchCount = lines.filter(v => v.trim() === entry.line).length;
      if (matchCount === 0) {
        // Owned line is absent — already removed or modified.
        removed.push(`${entry.relPath} (already absent)`); continue;
      }
      if (entry.ambiguous || matchCount > 1) {
        // Ambiguous: more than one matching line. Preserve all, retain ownership, and warn.
        retained.push(entry); skipped.push(`${entry.relPath} (ambiguous duplicate gitignore lines; preserved)`); continue;
      }
      // Exactly one match.
      let seen = 0; let index = -1;
      for (let i = 0; i < lines.length; i++) if (lines[i].trim() === entry.line) { if (seen++ === entry.occurrence) { index = i; break; } }
      if (index < 0) {
        // Occurrence index doesn't match — treat as already absent.
        removed.push(`${entry.relPath} (already absent)`); continue;
      }
      lines.splice(index, 1); writes.set(fullPath, lines.join(ending));
      if (entry.createdFile && lines.every(line => line === '')) deletes.push(fullPath); else removed.push(`${entry.relPath} (owned gitignore line removed)`);
      continue;
    }
    if (entry.kind === 'marker-block') {
      if (!existsSync(fullPath)) { removed.push(`${entry.relPath} (already absent)`); continue; }
      const original = writes.get(fullPath) ?? readFileSync(fullPath, 'utf8');
      const plan = computeGuidanceRemoval(original, entry);
      if (plan.outcome === 'absent') { removed.push(`${entry.relPath} (guidance block already absent)`); continue; }
      if (plan.outcome === 'modified') { retained.push(entry); skipped.push(`${entry.relPath} (guidance block modified since generation; preserved)`); continue; }
      if (plan.outcome === 'malformed') { retained.push(entry); skipped.push(`${entry.relPath} (guidance markers malformed; preserved)`); continue; }
      if (plan.outcome === 'delete') { deletes.push(fullPath); emptyCandidates.push(fullPath); removed.push(`${entry.relPath} (guidance block removed; created file deleted)`); continue; }
      if (plan.outcome === 'rewrite') {
        writes.set(fullPath, plan.content); removed.push(`${entry.relPath} (owned guidance block removed)`);
      } else {
        retained.push(entry); errors.push(`${entry.relPath}: unknown guidance removal plan '${plan.outcome}'`);
      }
      continue;
    }
    if (entry.nonReversible || !Array.isArray(entry.mutations) || !entry.mutations.length) {
      retained.push(entry); skipped.push(`${entry.relPath} (legacy shared mutation metadata is incomplete; preserved)`); continue;
    }
    if (!existsSync(fullPath)) { removed.push(`${entry.relPath} (already absent)`); continue; }
    try {
      const original = writes.get(fullPath) ?? readFileSync(fullPath, 'utf8');
      const ending = original.includes('\r\n') ? '\r\n' : '\n';
      const json = JSON.parse(original);
      if (!isPlainObject(json)) throw new Error('expected a JSON object');
      let reversible = true;
      let changed = false;
      for (const mutation of entry.mutations) {
        const parts = pointerParts(mutation.pointer);
        let parent = json;
        for (const part of parts.slice(0, -1)) parent = parent?.[part];
        const key = parts.at(-1);
        if (!parent || typeof parent !== 'object') { reversible = false; break; }
        if (mutation.op === 'array-add') {
          if (!Array.isArray(parent[key])) { reversible = false; break; }
          // Only reverse mutations that actually changed the file (added !== false).
          // Mutations with added: false were recorded for lineage but the value
          // was already present — removing it would delete user-owned content.
          if (mutation.added === false) continue;
          const index = parent[key].findIndex(value => same(value, mutation.value));
          if (index < 0) { reversible = false; break; }
          parent[key].splice(index, 1);
          changed = true;
        } else if (mutation.op === 'set-if-absent') {
          if (mutation.added === false) continue;
          if (!same(parent[key], mutation.value)) { reversible = false; break; }
          delete parent[key];
          changed = true;
        } else if (mutation.op === 'replace-array-element') {
          // A matching value that pre-existed generation was never owned.
          if (mutation.added === false) continue;
          if (!Array.isArray(parent[key])) { reversible = false; break; }
          const index = parent[key].findIndex(value => same(value, mutation.value));
          if (index < 0) { reversible = false; break; }
          if (Object.hasOwn(mutation, 'previous')) parent[key][index] = mutation.previous;
          else parent[key].splice(index, 1);
          changed = true;
        }
      }
      if (!reversible) { retained.push(entry); skipped.push(`${entry.relPath} (owned shared value modified; preserved)`); continue; }
      // Clean up createdContainers in reverse order (Defect 4).
      if (Array.isArray(entry.mutations)) {
        for (const mutation of [...entry.mutations].reverse()) {
          if (mutation.added === false) continue;
          if (!Array.isArray(mutation.createdContainers)) continue;
          for (const containerPointer of [...mutation.createdContainers].reverse()) {
            const parts = pointerParts(containerPointer);
            let parent = json;
            for (const part of parts.slice(0, -1)) parent = parent?.[part];
            const key = parts.at(-1);
            if (!parent || typeof parent !== 'object' || !(key in parent)) continue;
            const value = parent[key];
            const isEmpty = (isPlainObject(value) && Object.keys(value).length === 0) || (Array.isArray(value) && value.length === 0);
            if (isEmpty) { delete parent[key]; changed = true; }
          }
        }
      }
      const rendered = JSON.stringify(json, null, 2).replace(/\n/g, ending) + ending;
      // Delete the file only when Agentic Loop created it (createdFile: true)
      // and all mutations were reversed leaving no user content.
      // If the file pre-existed (even as {}), restore it to {} and preserve.
      if (changed && Object.keys(json).length === 0 && entry.createdFile) deletes.push(fullPath);
      else if (changed) writes.set(fullPath, rendered);
      if (changed) removed.push(`${entry.relPath} (owned shared mutation removed)`);
      else released.push(`${entry.relPath} (ownership released; pre-existing shared value preserved)`);
    } catch (error) { retained.push(entry); errors.push(`${entry.relPath}: ${error.message}`); }
  }
  if (dryRun) return { used: true, retained, valid: true, committed: false, removed, released, skipped, errors };
  const manifestPath = resolveManagedPath(targetRoot, '.', '.agenticloop/generated-artifacts.json');
  for (const path of deletes) if (existsSync(path)) removePath(path);
  for (const [path, content] of writes) if (!deletes.includes(path)) atomicWrite(path, content);
  if (retained.length) {
    if (activeRemovalTransaction) activeRemovalTransaction.mutateFile(manifestPath, () => saveManifest(targetRoot, { ...manifest, entries: retained }));
    else saveManifest(targetRoot, { ...manifest, entries: retained });
  }
  else if (existsSync(manifestPath)) removePath(manifestPath);
  for (const path of emptyCandidates) removeEmptyParents(targetRoot, dirname(path), removed, false);
  return { used: true, retained, valid: true, committed: true, removed, released, skipped, errors };
}

// ---------------------------------------------------------------------------
// Legacy marker-based removal (fallback when no manifest exists)
// ---------------------------------------------------------------------------

const CODEX_AGENT_GENERATED_MARKER = '# Generated by: agenticloop generate codex';
const CLAUDE_CODE_GENERATED_MARKER = 'Generated by: agenticloop generate claude-code';
const CLAUDE_CODE_ROLE_NAMES = ['orchestrator', 'maintainer', 'engineer', 'auditor'];
const CLAUDE_CODE_SETTINGS_ENTRIES = [
  '.claude/settings.json',
  '.claude/settings.local.json',
];

function readTextIfExistsTrimmed(path) {
  try {
    return existsSync(path) ? readFileSync(path, 'utf-8') : '';
  } catch {
    return '';
  }
}

function fileContainsMarker(filePath, marker) {
  const text = readTextIfExistsTrimmed(filePath);
  return text.includes(marker);
}

function isGeneratedCodexSkillDir(entry, fullPath) {
  const skillPath = join(fullPath, 'SKILL.md');
  const skillText = readTextIfExists(skillPath);
  if (!skillText) return false;
  if (skillText.includes(CODEX_GENERATED_MARKER)) return true;
  if (entry === CODEX_PUBLIC_SKILL_NAME) {
    return (
      /name:\s*["']?agenticloop["']?/i.test(skillText) &&
      existsSync(join(fullPath, 'agents', 'openai.yaml')) &&
      existsSync(join(fullPath, 'references', 'skills'))
    );
  }
  if (!GENERATED_LEGACY_CODEX_SKILL_NAMES.has(entry)) return false;
  const hasStrongMarker = skillText.includes(CODEX_GENERATED_MARKER);
  const hasLegacyStructure =
    existsSync(join(fullPath, 'agents', 'openai.yaml')) &&
    existsSync(join(fullPath, 'references', 'skills'));
  return hasStrongMarker || hasLegacyStructure;
}

function removeGeneratedCodexSkillDirs(targetRoot, removed, skipped, errors, dryRun) {
  const skillsRoot = join(targetRoot, '.agents', 'skills');
  if (!existsSync(skillsRoot) || !statSync(skillsRoot).isDirectory()) return;
  for (const entry of readdirSync(skillsRoot)) {
    if (entry !== CODEX_PUBLIC_SKILL_NAME && !entry.startsWith(CODEX_SKILL_PREFIX)) continue;
    const fullPath = join(skillsRoot, entry);
    if (!statSync(fullPath).isDirectory()) continue;
    if (!isGeneratedCodexSkillDir(entry, fullPath)) {
      skipped.push(`.agents/skills/${entry} (not recognized as generated Agentic Loop Codex output)`);
      continue;
    }
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) removePath(fullPath);
      removed.push(`.agents/skills/${entry}`);
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`.agents/skills/${entry}: ${error.message}`);
    }
  }
}

function removeAgenticLoopMarketplaceEntry(targetRoot, removed, skipped, errors, dryRun) {
  const marketplacePath = join(targetRoot, '.agents', 'plugins', 'marketplace.json');
  if (!existsSync(marketplacePath)) return;
  let parsed;
  try {
    parsed = JSON.parse(readFileSync(marketplacePath, 'utf-8'));
  } catch (error) {
    errors.push(`.agents/plugins/marketplace.json: ${error.message}`);
    return;
  }
  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    errors.push('.agents/plugins/marketplace.json: malformed JSON (preserved)');
    return;
  }
  const plugins = Array.isArray(parsed.plugins) ? parsed.plugins : [];
  if (!plugins.some(plugin => plugin?.name === 'agenticloop')) return;
  const remainingPlugins = plugins.filter(plugin => plugin?.name !== 'agenticloop');
  const otherKeys = Object.keys(parsed).filter(key => key !== 'plugins');
  const generatedInterface =
    parsed.interface &&
    typeof parsed.interface === 'object' &&
    !Array.isArray(parsed.interface) &&
    parsed.interface.displayName === 'Agentic Loop Local' &&
    Object.keys(parsed.interface).length === 1;
  const generatedOnly =
    remainingPlugins.length === 0 &&
    otherKeys.every(key => key === 'name' || key === 'description' || key === 'interface') &&
    parsed.name === GENERATED_CODEX_MARKETPLACE_NAME &&
    (!parsed.interface || generatedInterface);

  if (!dryRun) {
    if (generatedOnly) {
      removePath(marketplacePath);
    } else {
      const updated = { ...parsed, plugins: remainingPlugins };
      atomicWrite(marketplacePath, JSON.stringify(updated, null, 2) + '\n');
    }
  }
  removed.push(generatedOnly ? '.agents/plugins/marketplace.json' : '.agents/plugins/marketplace.json (agenticloop entry)');
  if (generatedOnly) {
    removeEmptyParents(targetRoot, dirname(marketplacePath), removed, dryRun);
  }
}

function removeGeneratedCopilotArtifacts(targetRoot, removed, skipped, errors, dryRun) {
  for (const fullPath of listGeneratedCopilotAgentFiles(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) removePath(fullPath);
      removed.push(toDisplayPath(fullPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(fullPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  }
  const skillPath = resolveCopilotPublicSkillPath(targetRoot);
  const skillDir = dirname(skillPath);
  if (isGeneratedCopilotSkill(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, skillDir);
      if (!dryRun) removePath(skillDir);
      removed.push(toDisplayPath(skillDir.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(skillDir.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(skillDir)) {
    skipped.push('.github/skills/agenticloop (not recognized as generated Agentic Loop Copilot output)');
  }
  const promptPath = resolveCopilotPromptPath(targetRoot);
  if (isGeneratedCopilotPrompt(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, promptPath);
      if (!dryRun) removePath(promptPath);
      removed.push(toDisplayPath(promptPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(promptPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(promptPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(promptPath)) {
    skipped.push('.github/prompts/agenticloop.prompt.md (not recognized as generated Agentic Loop Copilot output)');
  }
}

function removeGeneratedCursorArtifacts(targetRoot, removed, skipped, errors, dryRun) {
  for (const fullPath of listGeneratedCursorAgentFiles(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) removePath(fullPath);
      removed.push(toDisplayPath(fullPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(fullPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  }
  const skillPath = resolveCursorPublicSkillPath(targetRoot);
  const skillDir = dirname(skillPath);
  if (isGeneratedCursorSkill(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, skillDir);
      if (!dryRun) removePath(skillDir);
      removed.push(toDisplayPath(skillDir.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(skillDir.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(skillDir)) {
    skipped.push('.cursor/skills/agenticloop (not recognized as generated Agentic Loop Cursor output)');
  }
}

function removeGeneratedOpencodeFiles(targetRoot, removed, skipped, errors, dryRun) {
  for (const roleName of OPENCODE_ROLE_NAMES) {
    const relPath = OPENCODE_AGENT_RELATIVE_PATHS[roleName];
    const fullPath = join(targetRoot, relPath);
    if (!existsSync(fullPath)) continue;
    if (fileContainsMarker(fullPath, OPENCODE_GENERATED_BANNER)) {
      try {
        assertInsideTarget(targetRoot, fullPath);
        if (!dryRun) removePath(fullPath);
        removed.push(toDisplayPath(relPath));
        removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop OpenCode output)`);
    }
  }
  const commandRelPath = OPENCODE_COMMAND_RELATIVE_PATH;
  const commandFullPath = join(targetRoot, commandRelPath);
  if (existsSync(commandFullPath)) {
    if (fileContainsMarker(commandFullPath, OPENCODE_GENERATED_BANNER)) {
      try {
        assertInsideTarget(targetRoot, commandFullPath);
        if (!dryRun) removePath(commandFullPath);
        removed.push(toDisplayPath(commandRelPath));
        removeEmptyParents(targetRoot, dirname(commandFullPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(commandRelPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(commandRelPath)} (not recognized as generated Agentic Loop OpenCode output)`);
    }
  }
}

function removeGeneratedCodexAgentFiles(targetRoot, removed, skipped, errors, dryRun) {
  const agentsDir = join(targetRoot, '.codex', 'agents');
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return;
  for (const entry of readdirSync(agentsDir)) {
    if (!entry.endsWith('.toml')) continue;
    const fullPath = join(agentsDir, entry);
    if (!statSync(fullPath).isFile()) continue;
    const relPath = `.codex/agents/${entry}`;
    if (fileContainsMarker(fullPath, CODEX_AGENT_GENERATED_MARKER)) {
      try {
        assertInsideTarget(targetRoot, fullPath);
        if (!dryRun) removePath(fullPath);
        removed.push(toDisplayPath(relPath));
        removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop Codex output)`);
    }
  }
}

function removeGeneratedClaudeCodeFiles(targetRoot, removed, skipped, errors, dryRun) {
  const agentsDir = join(targetRoot, '.claude', 'agents');
  if (existsSync(agentsDir) && statSync(agentsDir).isDirectory()) {
    for (const entry of readdirSync(agentsDir)) {
      if (!entry.endsWith('.md')) continue;
      const agentPath = join(agentsDir, entry);
      if (!statSync(agentPath).isFile()) continue;
      const relPath = `.claude/agents/${entry}`;
      if (fileContainsMarker(agentPath, CLAUDE_CODE_GENERATED_MARKER)) {
        try {
          assertInsideTarget(targetRoot, agentPath);
          if (!dryRun) removePath(agentPath);
          removed.push(toDisplayPath(relPath));
          removeEmptyParents(targetRoot, dirname(agentPath), removed, dryRun);
        } catch (error) {
          errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
        }
      } else {
        skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop Claude Code output)`);
      }
    }
  }
  const commandPath = join(targetRoot, '.claude', 'commands', 'agenticloop.md');
  if (existsSync(commandPath)) {
    const relPath = '.claude/commands/agenticloop.md';
    if (fileContainsMarker(commandPath, CLAUDE_CODE_GENERATED_MARKER)) {
      try {
        assertInsideTarget(targetRoot, commandPath);
        if (!dryRun) removePath(commandPath);
        removed.push(toDisplayPath(relPath));
        removeEmptyParents(targetRoot, dirname(commandPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop Claude Code output)`);
    }
  }
  const skillDir = join(targetRoot, '.claude', 'skills', 'agenticloop');
  if (existsSync(skillDir) && statSync(skillDir).isDirectory()) {
    const skillPath = join(skillDir, 'SKILL.md');
    if (fileContainsMarker(skillPath, CLAUDE_CODE_GENERATED_MARKER)) {
      try {
        assertInsideTarget(targetRoot, skillDir);
        if (!dryRun) removePath(skillDir);
        removed.push('.claude/skills/agenticloop');
        removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
      } catch (error) {
        errors.push(`.claude/skills/agenticloop: ${error.message}`);
      }
    } else {
      skipped.push('.claude/skills/agenticloop (not recognized as generated Agentic Loop Claude Code output)');
    }
  }

  // Reverse Claude settings permissions that Agentic Loop added.
  for (const settingsEntry of CLAUDE_CODE_SETTINGS_ENTRIES) {
    const settingsPath = join(targetRoot, settingsEntry);
    if (!existsSync(settingsPath)) continue;
    try {
      const text = readFileSync(settingsPath, 'utf-8');
      const parsed = JSON.parse(text);
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
        errors.push(`${settingsEntry}: expected a JSON object`);
        continue;
      }
      if (!isPlainObject(parsed.permissions)) continue;

      const agenticLoopPatterns = [
        'Bash(npx agenticloop *)',
        'PowerShell(npx agenticloop *)',
      ];
      const originalAllow = Array.isArray(parsed.permissions.allow) ? parsed.permissions.allow : [];
      const filteredAllow = originalAllow.filter(entry => !agenticLoopPatterns.includes(entry));
      const originalDeny = Array.isArray(parsed.permissions.deny) ? parsed.permissions.deny : [];

      const hadOnlyAgenticLoopEntries =
        originalAllow.length > 0 &&
        filteredAllow.length === 0 &&
        originalDeny.length === 0 &&
        parsed.permissions.defaultMode === undefined;

      if (hadOnlyAgenticLoopEntries && Object.keys(parsed).length === 1 &&
        Object.keys(parsed.permissions).filter(k => k !== 'allow' && k !== 'deny').length === 0) {
        if (!dryRun) removePath(settingsPath);
        removed.push(toDisplayPath(settingsEntry));
        removeEmptyParents(targetRoot, dirname(settingsPath), removed, dryRun);
      } else if (filteredAllow.length !== originalAllow.length) {
        parsed.permissions.allow = filteredAllow;
        if (!dryRun) atomicWrite(settingsPath, JSON.stringify(parsed, null, 2) + '\n');
        removed.push(`${settingsEntry} (Agentic Loop permission entries removed)`);
      } else {
        skipped.push(`${settingsEntry} (no Agentic Loop permission entries found)`);
      }
    } catch (error) {
      errors.push(`${settingsEntry}: ${error.message}`);
    }
  }
}

function removeKnownPaths(targetRoot, removed, skipped, errors, dryRun, retainedEntries = []) {
  for (const relPath of DEFAULT_REMOVABLE_PATHS) {
    const fullPath = resolve(targetRoot, relPath);
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!existsSync(fullPath)) continue;
      if (relPath === 'plugins/agenticloop' && statSync(fullPath).isDirectory()) {
        // In manifest-backed mode, check if any retained manifest entries live
        // under this directory before deleting it (Defect 3).
        const hasRetainedContent = retainedEntries.some(entry => {
          try {
            const entryPath = resolveManagedPath(targetRoot, entry.outputRoot, entry.relPath);
            return entryPath.startsWith(fullPath + sep) || entryPath === fullPath;
          } catch { return false; }
        });
        if (hasRetainedContent) {
          skipped.push(`${toDisplayPath(relPath)} (preserved; contains files with active manifest ownership)`);
          continue;
        }
        const children = readdirSync(fullPath);
        const hasUnknownContent = children.some(child => {
          const childPath = join(fullPath, child);
          const isCodexPlugin = child === '.codex-plugin';
          const isCursorPlugin = child === '.cursor-plugin';
          const isSkillsDir = child === 'skills';
          return !isCodexPlugin && !isCursorPlugin && !isSkillsDir;
        });
        if (hasUnknownContent) {
          skipped.push(`${toDisplayPath(relPath)} (preserved; contains files not generated by Agentic Loop)`);
          continue;
        }
      }
      if (!dryRun) removePath(fullPath);
      removed.push(toDisplayPath(relPath));
      if (relPath === 'plugins/agenticloop') {
        removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
      }
    } catch (error) {
      errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
    }
  }
}

function removeOwnedLegacyCanonicalAssets(targetRoot, removed, skipped, errors, dryRun) {
  for (const asset of inspectLegacyCanonicalAssets(targetRoot)) {
    const fullPath = resolve(targetRoot, asset.legacyPath);
    if (!asset.owned) {
      skipped.push(`${asset.legacyPath} (legacy root path preserved; ownership not confirmed)`);
      continue;
    }
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) removePath(fullPath);
      removed.push(toDisplayPath(asset.legacyPath));
    } catch (error) {
      errors.push(`${asset.legacyPath}: ${error.message}`);
    }
  }
}

function maybeRemoveTargetState(targetRoot, removed, skipped, errors, dryRun, includeState) {
  const statePath = join(targetRoot, TARGET_STATE_DIRECTORY);
  if (!existsSync(statePath)) return;
  if (!includeState) {
    skipped.push('.agenticloop/ (preserved target-owned state)');
    return;
  }
  try {
    assertInsideTarget(targetRoot, statePath);
    if (!dryRun) removePath(statePath);
    removed.push('.agenticloop');
  } catch (error) {
    errors.push(`.agenticloop: ${error.message}`);
  }
}

/**
 * Remove known Agentic Loop assets.
 *
 * Manifest-first: when a manifest exists, uses it for precise removal.
 * Legacy fallback: marker-based recognition for pre-manifest installations.
 *
 * @param {object} options
 * @param {string} options.target
 * @param {boolean} options.dryRun
 * @param {boolean} [options.includeState=false]
 * @returns {{ removed: string[], released: string[], skipped: string[], errors: string[], committed: boolean, cleanupErrors: string[], rollbackIncomplete: boolean, recoveryJournal: string|null }}
 */
export function executeRemovalPlan(targetRoot, { dryRun = false, includeState = false } = {}, hooks = {}) {
  const removed = [];
  const released = [];
  const skipped = [];
  const errors = [];
  if (activeRemovalTransaction) {
    return {
      removed, released, skipped, committed: false, cleanupErrors: [],
      rollbackIncomplete: false, recoveryJournal: null,
      errors: ['A removal transaction is already active for this process; nested removal is not supported.'],
    };
  }
  const transaction = dryRun ? null : new RemovalTransaction(targetRoot, hooks);
  activeRemovalTransaction = transaction;
  try {
    // A malformed manifest is a hard planning failure; no heuristic cleanup is
    // permitted after it, even in the command-wide transaction.
    const manifestResult = removeWithManifest(targetRoot, dryRun);
    const { used: manifestUsed, retained, valid: manifestValid } = manifestResult;
    removed.push(...manifestResult.removed);
    released.push(...manifestResult.released);
    skipped.push(...manifestResult.skipped);
    errors.push(...manifestResult.errors);
    if (manifestUsed && !manifestValid) {
      const cleanupErrors = transaction?.abort() ?? [];
      return { removed, released, skipped, errors, committed: false, cleanupErrors, rollbackIncomplete: false, recoveryJournal: null };
    }

    hooks.afterOutputWrites?.();
    if (manifestUsed) {
      removeKnownPaths(targetRoot, removed, skipped, errors, dryRun, retained);
    } else {
      removeKnownPaths(targetRoot, removed, skipped, errors, dryRun);
      removeGeneratedOpencodeFiles(targetRoot, removed, skipped, errors, dryRun);
      removeGeneratedCodexAgentFiles(targetRoot, removed, skipped, errors, dryRun);
      removeGeneratedClaudeCodeFiles(targetRoot, removed, skipped, errors, dryRun);
      removeOwnedLegacyCanonicalAssets(targetRoot, removed, skipped, errors, dryRun);
      removeGeneratedCodexSkillDirs(targetRoot, removed, skipped, errors, dryRun);
      removeAgenticLoopMarketplaceEntry(targetRoot, removed, skipped, errors, dryRun);
      removeGeneratedCopilotArtifacts(targetRoot, removed, skipped, errors, dryRun);
      removeGeneratedCursorArtifacts(targetRoot, removed, skipped, errors, dryRun);
    }
    hooks.afterKnownPathStaging?.();
    maybeRemoveTargetState(targetRoot, removed, skipped, errors, dryRun, includeState);
    hooks.beforeFinalize?.();
    if (errors.length) throw new Error(errors.join('; '));
    transaction?.markCommitted();
    const cleanupErrors = transaction?.cleanupQuarantine() ?? [];
    return { removed, released, skipped, errors, committed: !dryRun, cleanupErrors, rollbackIncomplete: false, recoveryJournal: null };
  } catch (error) {
    const rollback = transaction?.rollback() ?? { completed: true, errors: [], journalPath: null };
    const recovery = rollback.journalPath ? `; recovery journal retained at ${rollback.journalPath}` : '';
    const summary = rollback.completed
      ? `Removal transaction failed and rolled back: ${error.message}`
      : `Removal transaction failed and rollback is incomplete${recovery}: ${error.message}`;
    return {
      removed: [],
      released: [],
      skipped: [],
      committed: false,
      cleanupErrors: [],
      rollbackIncomplete: !rollback.completed,
      recoveryJournal: rollback.journalPath,
      errors: [summary, ...rollback.errors],
    };
  } finally {
    activeRemovalTransaction = null;
  }
}

export function removeAgenticLoop(options = {}) {
  const targetRoot = resolve(options.target ?? process.cwd());
  if (isPackageSourceRepositoryRoot(targetRoot)) {
    return {
      removed: [], released: [], skipped: [],
      committed: false, cleanupErrors: [],
      rollbackIncomplete: false, recoveryJournal: null,
      errors: [`Refusing to mutate the Agentic Loop package source repository at ${targetRoot}. Use --target to point at a downstream project directory.`],
    };
  }
  return executeRemovalPlan(targetRoot, {
    dryRun: Boolean(options.dryRun),
    includeState: Boolean(options.includeState),
  });
}
