/**
 * Remove Agentic Loop overlay files from a target directory.
 *
 * This command removes toolkit-owned source and generated adapter artifacts.
 * Target-owned .agenticloop/ state is preserved by default.
 */

import { existsSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import {
  INSTALLED_TOOLKIT_ROOT_DIRECTORY,
  TARGET_STATE_DIRECTORY,
  isPackageSourceRepositoryRoot,
} from './layout.js';
import { inspectLegacyCanonicalAssets } from './layout-migration.js';
import {
  isGeneratedCopilotPrompt,
  isGeneratedCopilotSkill,
  listGeneratedCopilotAgentFiles,
  resolveCopilotPromptPath,
  resolveCopilotPublicSkillPath,
} from './adapters/copilot.js';
import {
  isGeneratedCursorSkill,
  listGeneratedCursorAgentFiles,
  resolveCursorPublicSkillPath,
} from './adapters/cursor.js';

const DEFAULT_REMOVABLE_PATHS = [
  INSTALLED_TOOLKIT_ROOT_DIRECTORY,
  'agenticloop.json',
  '.opencode',
  '.codex',
  '.claude',
  'plugins/agenticloop',
];

const CODEX_PUBLIC_SKILL_NAME = 'agenticloop';
const CODEX_SKILL_PREFIX = 'agenticloop-';
const CODEX_GENERATED_MARKER = 'Generated by: agenticloop generate codex';
const GENERATED_CODEX_MARKETPLACE_NAME = 'agenticloop-local';
const GENERATED_LEGACY_CODEX_SKILL_NAMES = new Set([
  'agenticloop-start',
  'agenticloop-blocked-state',
  'agenticloop-change-request-gate',
  'agenticloop-debugging-before-fixes',
  'agenticloop-decision-capture',
  'agenticloop-frontend-design-quality',
  'agenticloop-github-attribution',
  'agenticloop-loop-retrospective',
  'agenticloop-ponytail',
  'agenticloop-review-and-accept',
  'agenticloop-role-delegation',
  'agenticloop-setup-agenticloop',
  'agenticloop-task-closeout',
  'agenticloop-task-record-contract',
  'agenticloop-tdd-implementation',
  'agenticloop-verification-evidence',
]);

function toDisplayPath(relPath) {
  return relPath.replace(/\\/g, '/');
}

function assertInsideTarget(targetRoot, fullPath) {
  const resolved = resolve(fullPath);
  if (resolved !== targetRoot && !resolved.startsWith(`${targetRoot}${sep}`)) {
    throw new Error(`Refusing to remove path outside target: ${resolved}`);
  }
}

function isEmptyDir(path) {
  return existsSync(path) && statSync(path).isDirectory() && readdirSync(path).length === 0;
}

function removeEmptyParents(targetRoot, startDir, removed, dryRun) {
  let current = startDir;
  while (current !== targetRoot && current.startsWith(`${targetRoot}${sep}`)) {
    if (!isEmptyDir(current)) return;
    const rel = toDisplayPath(current.slice(targetRoot.length + 1));
    if (!dryRun) rmSync(current, { recursive: true, force: true });
    removed.push(rel);
    current = dirname(current);
  }
}

function readTextIfExists(path) {
  try {
    return existsSync(path) ? readFileSync(path, 'utf-8') : '';
  } catch {
    return '';
  }
}

function isGeneratedCodexSkillDir(entry, fullPath) {
  const skillPath = join(fullPath, 'SKILL.md');
  const skillText = readTextIfExists(skillPath);
  if (!skillText) return false;
  if (skillText.includes(CODEX_GENERATED_MARKER)) return true;

  if (entry === CODEX_PUBLIC_SKILL_NAME) {
    return (
      /name:\s*["']?agenticloop["']?/i.test(skillText) &&
      existsSync(join(fullPath, 'agents', 'openai.yaml')) &&
      existsSync(join(fullPath, 'references', 'skills'))
    );
  }

  return GENERATED_LEGACY_CODEX_SKILL_NAMES.has(entry);
}

function removeGeneratedCodexSkillDirs(targetRoot, removed, skipped, errors, dryRun) {
  const skillsRoot = join(targetRoot, '.agents', 'skills');
  if (!existsSync(skillsRoot) || !statSync(skillsRoot).isDirectory()) return;

  for (const entry of readdirSync(skillsRoot)) {
    if (entry !== CODEX_PUBLIC_SKILL_NAME && !entry.startsWith(CODEX_SKILL_PREFIX)) continue;
    const fullPath = join(skillsRoot, entry);
    if (!statSync(fullPath).isDirectory()) continue;
    if (!isGeneratedCodexSkillDir(entry, fullPath)) {
      skipped.push(`.agents/skills/${entry} (not recognized as generated Agentic Loop Codex output)`);
      continue;
    }
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { recursive: true, force: true });
      removed.push(`.agents/skills/${entry}`);
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`.agents/skills/${entry}: ${error.message}`);
    }
  }
}

function removeAgenticLoopMarketplaceEntry(targetRoot, removed, errors, dryRun) {
  const marketplacePath = join(targetRoot, '.agents', 'plugins', 'marketplace.json');
  if (!existsSync(marketplacePath)) return;

  let parsed;
  try {
    parsed = JSON.parse(readFileSync(marketplacePath, 'utf-8'));
  } catch (error) {
    errors.push(`.agents/plugins/marketplace.json: ${error.message}`);
    return;
  }

  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    errors.push('.agents/plugins/marketplace.json: expected a JSON object');
    return;
  }

  const plugins = Array.isArray(parsed.plugins) ? parsed.plugins : [];
  if (!plugins.some(plugin => plugin?.name === 'agenticloop')) return;

  const remainingPlugins = plugins.filter(plugin => plugin?.name !== 'agenticloop');
  const otherKeys = Object.keys(parsed).filter(key => key !== 'plugins');
  const generatedInterface =
    parsed.interface &&
    typeof parsed.interface === 'object' &&
    !Array.isArray(parsed.interface) &&
    parsed.interface.displayName === 'Agentic Loop Local' &&
    Object.keys(parsed.interface).length === 1;
  const generatedOnly =
    remainingPlugins.length === 0 &&
    otherKeys.every(key => key === 'name' || key === 'description' || key === 'interface') &&
    parsed.name === GENERATED_CODEX_MARKETPLACE_NAME &&
    (!parsed.interface || generatedInterface);

  if (!dryRun) {
    if (generatedOnly) {
      rmSync(marketplacePath, { force: true });
    } else {
      const updated = { ...parsed, plugins: remainingPlugins };
      writeFileSync(marketplacePath, JSON.stringify(updated, null, 2) + '\n', 'utf-8');
    }
  }

  removed.push(generatedOnly ? '.agents/plugins/marketplace.json' : '.agents/plugins/marketplace.json (agenticloop entry)');
  if (generatedOnly) {
    removeEmptyParents(targetRoot, dirname(marketplacePath), removed, dryRun);
  }
}

function removeGeneratedCopilotArtifacts(targetRoot, removed, skipped, errors, dryRun) {
  for (const fullPath of listGeneratedCopilotAgentFiles(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { force: true });
      removed.push(toDisplayPath(fullPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(fullPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  }

  const skillPath = resolveCopilotPublicSkillPath(targetRoot);
  const skillDir = dirname(skillPath);
  if (isGeneratedCopilotSkill(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, skillDir);
      if (!dryRun) rmSync(skillDir, { recursive: true, force: true });
      removed.push(toDisplayPath(skillDir.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(skillDir.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(skillDir)) {
    skipped.push('.github/skills/agenticloop (not recognized as generated Agentic Loop Copilot output)');
  }

  const promptPath = resolveCopilotPromptPath(targetRoot);
  if (isGeneratedCopilotPrompt(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, promptPath);
      if (!dryRun) rmSync(promptPath, { force: true });
      removed.push(toDisplayPath(promptPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(promptPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(promptPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(promptPath)) {
    skipped.push('.github/prompts/agenticloop.prompt.md (not recognized as generated Agentic Loop Copilot output)');
  }
}

function removeGeneratedCursorArtifacts(targetRoot, removed, skipped, errors, dryRun) {
  for (const fullPath of listGeneratedCursorAgentFiles(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { force: true });
      removed.push(toDisplayPath(fullPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(fullPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  }

  const skillPath = resolveCursorPublicSkillPath(targetRoot);
  const skillDir = dirname(skillPath);
  if (isGeneratedCursorSkill(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, skillDir);
      if (!dryRun) rmSync(skillDir, { recursive: true, force: true });
      removed.push(toDisplayPath(skillDir.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(skillDir.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(skillDir)) {
    skipped.push('.cursor/skills/agenticloop (not recognized as generated Agentic Loop Cursor output)');
  }
}

function removeKnownPaths(targetRoot, removed, errors, dryRun) {
  for (const relPath of DEFAULT_REMOVABLE_PATHS) {
    const fullPath = resolve(targetRoot, relPath);
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!existsSync(fullPath)) continue;
      if (!dryRun) rmSync(fullPath, { recursive: true, force: true });
      removed.push(toDisplayPath(relPath));
      if (relPath === 'plugins/agenticloop') {
        removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
      }
    } catch (error) {
      errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
    }
  }
}

function removeOwnedLegacyCanonicalAssets(targetRoot, removed, skipped, errors, dryRun) {
  for (const asset of inspectLegacyCanonicalAssets(targetRoot)) {
    const fullPath = resolve(targetRoot, asset.legacyPath);
    if (!asset.owned) {
      skipped.push(`${asset.legacyPath} (legacy root path preserved; ownership not confirmed)`);
      continue;
    }
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { recursive: true, force: true });
      removed.push(toDisplayPath(asset.legacyPath));
    } catch (error) {
      errors.push(`${asset.legacyPath}: ${error.message}`);
    }
  }
}

function maybeRemoveTargetState(targetRoot, removed, skipped, errors, dryRun, includeState) {
  const statePath = join(targetRoot, TARGET_STATE_DIRECTORY);
  if (!existsSync(statePath)) return;
  if (!includeState) {
    skipped.push('.agenticloop/ (preserved target-owned state)');
    return;
  }
  try {
    assertInsideTarget(targetRoot, statePath);
    if (!dryRun) rmSync(statePath, { recursive: true, force: true });
    removed.push('.agenticloop');
  } catch (error) {
    errors.push(`.agenticloop: ${error.message}`);
  }
}

/**
 * Remove known Agentic Loop assets.
 *
 * @param {object} options
 * @param {string} options.target
 * @param {boolean} options.dryRun
 * @param {boolean} [options.includeState=false]
 * @returns {{ removed: string[], skipped: string[], errors: string[] }}
 */
export function removeAgenticLoop(options) {
  const targetRoot = resolve(options.target ?? process.cwd());
  const dryRun = Boolean(options.dryRun);
  const includeState = Boolean(options.includeState);
  const removed = [];
  const skipped = [];
  const errors = [];

  if (isPackageSourceRepositoryRoot(targetRoot)) {
    errors.push(
      `Refusing to mutate the Agentic Loop package source repository at ${targetRoot}. Use --target to point at a downstream project directory.`
    );
    return { removed, skipped, errors };
  }

  removeKnownPaths(targetRoot, removed, errors, dryRun);
  removeOwnedLegacyCanonicalAssets(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedCodexSkillDirs(targetRoot, removed, skipped, errors, dryRun);
  removeAgenticLoopMarketplaceEntry(targetRoot, removed, errors, dryRun);
  removeGeneratedCopilotArtifacts(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedCursorArtifacts(targetRoot, removed, skipped, errors, dryRun);
  maybeRemoveTargetState(targetRoot, removed, skipped, errors, dryRun, includeState);

  return { removed, skipped, errors };
}
