/**
 * Remove Agentic Loop overlay files from a target directory.
 *
 * This command removes toolkit-owned source and generated adapter artifacts.
 * Target-owned .agenticloop/ state is preserved by default.
 */

import { existsSync, readFileSync, readdirSync, rmSync, statSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve, sep } from 'node:path';
import {
  INSTALLED_TOOLKIT_ROOT_DIRECTORY,
  TARGET_STATE_DIRECTORY,
  isPackageSourceRepositoryRoot,
} from './layout.js';
import { inspectLegacyCanonicalAssets } from './layout-migration.js';
import {
  OPENCODE_ROLE_NAMES,
  OPENCODE_AGENT_RELATIVE_PATHS,
  OPENCODE_COMMAND_RELATIVE_PATH,
  GENERATED_BANNER as OPENCODE_GENERATED_BANNER,
} from './adapters/opencode.js';
import {
  isGeneratedCopilotPrompt,
  isGeneratedCopilotSkill,
  listGeneratedCopilotAgentFiles,
  resolveCopilotPromptPath,
  resolveCopilotPublicSkillPath,
} from './adapters/copilot.js';
import {
  isGeneratedCursorSkill,
  listGeneratedCursorAgentFiles,
  resolveCursorPublicSkillPath,
} from './adapters/cursor.js';

const DEFAULT_REMOVABLE_PATHS = [
  INSTALLED_TOOLKIT_ROOT_DIRECTORY,
  'agenticloop.json',
  'plugins/agenticloop',
];

const CODEX_PUBLIC_SKILL_NAME = 'agenticloop';
const CODEX_SKILL_PREFIX = 'agenticloop-';
const CODEX_GENERATED_MARKER = 'Generated by: agenticloop generate codex';
const GENERATED_CODEX_MARKETPLACE_NAME = 'agenticloop-local';
const GENERATED_LEGACY_CODEX_SKILL_NAMES = new Set([
  'agenticloop-start',
  'agenticloop-blocked-state',
  'agenticloop-change-request-gate',
  'agenticloop-debugging-before-fixes',
  'agenticloop-decision-capture',
  'agenticloop-frontend-design-quality',
  'agenticloop-github-attribution',
  'agenticloop-loop-retrospective',
  'agenticloop-ponytail',
  'agenticloop-review-and-accept',
  'agenticloop-role-delegation',
  'agenticloop-setup-agenticloop',
  'agenticloop-task-closeout',
  'agenticloop-task-record-contract',
  'agenticloop-tdd-implementation',
  'agenticloop-verification-evidence',
]);

function toDisplayPath(relPath) {
  return relPath.replace(/\\/g, '/');
}

function isPlainObject(value) {
  return !!value && typeof value === 'object' && !Array.isArray(value);
}

function assertInsideTarget(targetRoot, fullPath) {
  const resolved = resolve(fullPath);
  if (resolved !== targetRoot && !resolved.startsWith(`${targetRoot}${sep}`)) {
    throw new Error(`Refusing to remove path outside target: ${resolved}`);
  }
}

function isEmptyDir(path) {
  return existsSync(path) && statSync(path).isDirectory() && readdirSync(path).length === 0;
}

function removeEmptyParents(targetRoot, startDir, removed, dryRun) {
  let current = startDir;
  while (current !== targetRoot && current.startsWith(`${targetRoot}${sep}`)) {
    if (!isEmptyDir(current)) return;
    const rel = toDisplayPath(current.slice(targetRoot.length + 1));
    if (!dryRun) rmSync(current, { recursive: true, force: true });
    removed.push(rel);
    current = dirname(current);
  }
}

function readTextIfExists(path) {
  try {
    return existsSync(path) ? readFileSync(path, 'utf-8') : '';
  } catch {
    return '';
  }
}

function isGeneratedCodexSkillDir(entry, fullPath) {
  const skillPath = join(fullPath, 'SKILL.md');
  const skillText = readTextIfExists(skillPath);
  if (!skillText) return false;
  if (skillText.includes(CODEX_GENERATED_MARKER)) return true;

  // Public skill: require both the generated marker AND the exact known structure.
  if (entry === CODEX_PUBLIC_SKILL_NAME) {
    return (
      /name:\s*["']?agenticloop["']?/i.test(skillText) &&
      existsSync(join(fullPath, 'agents', 'openai.yaml')) &&
      existsSync(join(fullPath, 'references', 'skills'))
    );
  }

  // Legacy skills: require a strong marker or exact generated structure.
  // Do NOT delete based on directory name alone — a hand-authored skill
  // using one of these names must survive.
  if (!GENERATED_LEGACY_CODEX_SKILL_NAMES.has(entry)) return false;
  const hasStrongMarker = skillText.includes(CODEX_GENERATED_MARKER);
  const hasLegacyStructure =
    existsSync(join(fullPath, 'agents', 'openai.yaml')) &&
    existsSync(join(fullPath, 'references', 'skills'));
  return hasStrongMarker || hasLegacyStructure;
}

function removeGeneratedCodexSkillDirs(targetRoot, removed, skipped, errors, dryRun) {
  const skillsRoot = join(targetRoot, '.agents', 'skills');
  if (!existsSync(skillsRoot) || !statSync(skillsRoot).isDirectory()) return;

  for (const entry of readdirSync(skillsRoot)) {
    if (entry !== CODEX_PUBLIC_SKILL_NAME && !entry.startsWith(CODEX_SKILL_PREFIX)) continue;
    const fullPath = join(skillsRoot, entry);
    if (!statSync(fullPath).isDirectory()) continue;
    if (!isGeneratedCodexSkillDir(entry, fullPath)) {
      skipped.push(`.agents/skills/${entry} (not recognized as generated Agentic Loop Codex output)`);
      continue;
    }
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { recursive: true, force: true });
      removed.push(`.agents/skills/${entry}`);
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`.agents/skills/${entry}: ${error.message}`);
    }
  }
}

function removeAgenticLoopMarketplaceEntry(targetRoot, removed, skipped, errors, dryRun) {
  const marketplacePath = join(targetRoot, '.agents', 'plugins', 'marketplace.json');
  if (!existsSync(marketplacePath)) return;

  let parsed;
  try {
    parsed = JSON.parse(readFileSync(marketplacePath, 'utf-8'));
  } catch (error) {
    errors.push(`.agents/plugins/marketplace.json: ${error.message}`);
    return;
  }

  if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
    // Malformed marketplace JSON: preserve byte-for-byte.
    errors.push('.agents/plugins/marketplace.json: malformed JSON (preserved)');
    return;
  }

  const plugins = Array.isArray(parsed.plugins) ? parsed.plugins : [];
  if (!plugins.some(plugin => plugin?.name === 'agenticloop')) return;

  const remainingPlugins = plugins.filter(plugin => plugin?.name !== 'agenticloop');
  const otherKeys = Object.keys(parsed).filter(key => key !== 'plugins');
  const generatedInterface =
    parsed.interface &&
    typeof parsed.interface === 'object' &&
    !Array.isArray(parsed.interface) &&
    parsed.interface.displayName === 'Agentic Loop Local' &&
    Object.keys(parsed.interface).length === 1;
  const generatedOnly =
    remainingPlugins.length === 0 &&
    otherKeys.every(key => key === 'name' || key === 'description' || key === 'interface') &&
    parsed.name === GENERATED_CODEX_MARKETPLACE_NAME &&
    (!parsed.interface || generatedInterface);

  if (!dryRun) {
    if (generatedOnly) {
      rmSync(marketplacePath, { force: true });
    } else {
      const updated = { ...parsed, plugins: remainingPlugins };
      writeFileSync(marketplacePath, JSON.stringify(updated, null, 2) + '\n', 'utf-8');
    }
  }

  removed.push(generatedOnly ? '.agents/plugins/marketplace.json' : '.agents/plugins/marketplace.json (agenticloop entry)');
  if (generatedOnly) {
    removeEmptyParents(targetRoot, dirname(marketplacePath), removed, dryRun);
  }
}

function removeGeneratedCopilotArtifacts(targetRoot, removed, skipped, errors, dryRun) {
  for (const fullPath of listGeneratedCopilotAgentFiles(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { force: true });
      removed.push(toDisplayPath(fullPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(fullPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  }

  const skillPath = resolveCopilotPublicSkillPath(targetRoot);
  const skillDir = dirname(skillPath);
  if (isGeneratedCopilotSkill(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, skillDir);
      if (!dryRun) rmSync(skillDir, { recursive: true, force: true });
      removed.push(toDisplayPath(skillDir.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(skillDir.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(skillDir)) {
    skipped.push('.github/skills/agenticloop (not recognized as generated Agentic Loop Copilot output)');
  }

  const promptPath = resolveCopilotPromptPath(targetRoot);
  if (isGeneratedCopilotPrompt(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, promptPath);
      if (!dryRun) rmSync(promptPath, { force: true });
      removed.push(toDisplayPath(promptPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(promptPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(promptPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(promptPath)) {
    skipped.push('.github/prompts/agenticloop.prompt.md (not recognized as generated Agentic Loop Copilot output)');
  }
}

function removeGeneratedCursorArtifacts(targetRoot, removed, skipped, errors, dryRun) {
  for (const fullPath of listGeneratedCursorAgentFiles(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { force: true });
      removed.push(toDisplayPath(fullPath.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(fullPath.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  }

  const skillPath = resolveCursorPublicSkillPath(targetRoot);
  const skillDir = dirname(skillPath);
  if (isGeneratedCursorSkill(targetRoot)) {
    try {
      assertInsideTarget(targetRoot, skillDir);
      if (!dryRun) rmSync(skillDir, { recursive: true, force: true });
      removed.push(toDisplayPath(skillDir.slice(targetRoot.length + 1)));
      removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
    } catch (error) {
      errors.push(`${toDisplayPath(skillDir.slice(targetRoot.length + 1))}: ${error.message}`);
    }
  } else if (existsSync(skillDir)) {
    skipped.push('.cursor/skills/agenticloop (not recognized as generated Agentic Loop Cursor output)');
  }
}

const CODEX_AGENT_GENERATED_MARKER = '# Generated by: agenticloop generate codex';
const CLAUDE_CODE_GENERATED_MARKER = 'Generated by: agenticloop generate claude-code';
const CLAUDE_CODE_ROLE_NAMES = ['orchestrator', 'maintainer', 'engineer'];
const CLAUDE_CODE_SETTINGS_ENTRIES = [
  '.claude/settings.json',
  '.claude/settings.local.json',
];

function readTextIfExistsTrimmed(path) {
  try {
    return existsSync(path) ? readFileSync(path, 'utf-8') : '';
  } catch {
    return '';
  }
}

function fileContainsMarker(filePath, marker) {
  const text = readTextIfExistsTrimmed(filePath);
  return text.includes(marker);
}

function removeGeneratedOpencodeFiles(targetRoot, removed, skipped, errors, dryRun) {
  // Remove only recognized generated agent files.
  for (const roleName of OPENCODE_ROLE_NAMES) {
    const relPath = OPENCODE_AGENT_RELATIVE_PATHS[roleName];
    const fullPath = join(targetRoot, relPath);
    if (!existsSync(fullPath)) continue;
    if (fileContainsMarker(fullPath, OPENCODE_GENERATED_BANNER)) {
      try {
        assertInsideTarget(targetRoot, fullPath);
        if (!dryRun) rmSync(fullPath, { force: true });
        removed.push(toDisplayPath(relPath));
        removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop OpenCode output)`);
    }
  }

  // Remove only the recognized generated command file.
  const commandRelPath = OPENCODE_COMMAND_RELATIVE_PATH;
  const commandFullPath = join(targetRoot, commandRelPath);
  if (existsSync(commandFullPath)) {
    if (fileContainsMarker(commandFullPath, OPENCODE_GENERATED_BANNER)) {
      try {
        assertInsideTarget(targetRoot, commandFullPath);
        if (!dryRun) rmSync(commandFullPath, { force: true });
        removed.push(toDisplayPath(commandRelPath));
        removeEmptyParents(targetRoot, dirname(commandFullPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(commandRelPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(commandRelPath)} (not recognized as generated Agentic Loop OpenCode output)`);
    }
  }
}

function removeGeneratedCodexAgentFiles(targetRoot, removed, skipped, errors, dryRun) {
  const agentsDir = join(targetRoot, '.codex', 'agents');
  if (!existsSync(agentsDir) || !statSync(agentsDir).isDirectory()) return;

  for (const entry of readdirSync(agentsDir)) {
    if (!entry.endsWith('.toml')) continue;
    const fullPath = join(agentsDir, entry);
    if (!statSync(fullPath).isFile()) continue;
    const relPath = `.codex/agents/${entry}`;
    if (fileContainsMarker(fullPath, CODEX_AGENT_GENERATED_MARKER)) {
      try {
        assertInsideTarget(targetRoot, fullPath);
        if (!dryRun) rmSync(fullPath, { force: true });
        removed.push(toDisplayPath(relPath));
        removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop Codex output)`);
    }
  }
}

function removeGeneratedClaudeCodeFiles(targetRoot, removed, skipped, errors, dryRun) {
  // Scan ALL .md files in .claude/agents/ for the generated marker.
  // This supports custom roleBindings filenames, not just the default names.
  const agentsDir = join(targetRoot, '.claude', 'agents');
  if (existsSync(agentsDir) && statSync(agentsDir).isDirectory()) {
    for (const entry of readdirSync(agentsDir)) {
      if (!entry.endsWith('.md')) continue;
      const agentPath = join(agentsDir, entry);
      if (!statSync(agentPath).isFile()) continue;
      const relPath = `.claude/agents/${entry}`;
      if (fileContainsMarker(agentPath, CLAUDE_CODE_GENERATED_MARKER)) {
        try {
          assertInsideTarget(targetRoot, agentPath);
          if (!dryRun) rmSync(agentPath, { force: true });
          removed.push(toDisplayPath(relPath));
          removeEmptyParents(targetRoot, dirname(agentPath), removed, dryRun);
        } catch (error) {
          errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
        }
      } else {
        skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop Claude Code output)`);
      }
    }
  }

  // Remove only the recognized generated command file.
  const commandPath = join(targetRoot, '.claude', 'commands', 'agenticloop.md');
  if (existsSync(commandPath)) {
    const relPath = '.claude/commands/agenticloop.md';
    if (fileContainsMarker(commandPath, CLAUDE_CODE_GENERATED_MARKER)) {
      try {
        assertInsideTarget(targetRoot, commandPath);
        if (!dryRun) rmSync(commandPath, { force: true });
        removed.push(toDisplayPath(relPath));
        removeEmptyParents(targetRoot, dirname(commandPath), removed, dryRun);
      } catch (error) {
        errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
      }
    } else {
      skipped.push(`${toDisplayPath(relPath)} (not recognized as generated Agentic Loop Claude Code output)`);
    }
  }

  // Remove only the recognized generated public skill directory.
  const skillDir = join(targetRoot, '.claude', 'skills', 'agenticloop');
  if (existsSync(skillDir) && statSync(skillDir).isDirectory()) {
    const skillPath = join(skillDir, 'SKILL.md');
    if (fileContainsMarker(skillPath, CLAUDE_CODE_GENERATED_MARKER)) {
      try {
        assertInsideTarget(targetRoot, skillDir);
        if (!dryRun) rmSync(skillDir, { recursive: true, force: true });
        removed.push('.claude/skills/agenticloop');
        removeEmptyParents(targetRoot, dirname(skillDir), removed, dryRun);
      } catch (error) {
        errors.push(`.claude/skills/agenticloop: ${error.message}`);
      }
    } else {
      skipped.push('.claude/skills/agenticloop (not recognized as generated Agentic Loop Claude Code output)');
    }
  }

  // Reverse Claude settings permissions that Agentic Loop added.
  for (const settingsEntry of CLAUDE_CODE_SETTINGS_ENTRIES) {
    const settingsPath = join(targetRoot, settingsEntry);
    if (!existsSync(settingsPath)) continue;
    try {
      const text = readFileSync(settingsPath, 'utf-8');
      const parsed = JSON.parse(text);
      if (!parsed || typeof parsed !== 'object' || Array.isArray(parsed)) {
        errors.push(`${settingsEntry}: expected a JSON object`);
        continue;
      }
      if (!isPlainObject(parsed.permissions)) continue;

      const agenticLoopPatterns = [
        'Bash(npx agenticloop *)',
        'PowerShell(npx agenticloop *)',
      ];
      const originalAllow = Array.isArray(parsed.permissions.allow) ? parsed.permissions.allow : [];
      const filteredAllow = originalAllow.filter(entry => !agenticLoopPatterns.includes(entry));
      const originalDeny = Array.isArray(parsed.permissions.deny) ? parsed.permissions.deny : [];

      const hadOnlyAgenticLoopEntries =
        originalAllow.length > 0 &&
        filteredAllow.length === 0 &&
        originalDeny.length === 0 &&
        parsed.permissions.defaultMode === undefined;

      if (hadOnlyAgenticLoopEntries && Object.keys(parsed).length === 1 &&
        Object.keys(parsed.permissions).filter(k => k !== 'allow' && k !== 'deny').length === 0) {
        // Agentic Loop created the entire file; remove it.
        if (!dryRun) rmSync(settingsPath, { force: true });
        removed.push(toDisplayPath(settingsEntry));
        removeEmptyParents(targetRoot, dirname(settingsPath), removed, dryRun);
      } else if (filteredAllow.length !== originalAllow.length) {
        // Remove only the Agentic Loop entries.
        parsed.permissions.allow = filteredAllow;
        if (!dryRun) writeFileSync(settingsPath, JSON.stringify(parsed, null, 2) + '\n', 'utf-8');
        removed.push(`${settingsEntry} (Agentic Loop permission entries removed)`);
      } else {
        skipped.push(`${settingsEntry} (no Agentic Loop permission entries found)`);
      }
    } catch (error) {
      errors.push(`${settingsEntry}: ${error.message}`);
    }
  }
}

function removeKnownPaths(targetRoot, removed, skipped, errors, dryRun) {
  for (const relPath of DEFAULT_REMOVABLE_PATHS) {
    const fullPath = resolve(targetRoot, relPath);
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!existsSync(fullPath)) continue;

      // plugins/agenticloop: only remove if it contains only recognized
      // generated content (Codex/Cursor plugin artifacts). Preserve any
      // unknown or user-added files.
      if (relPath === 'plugins/agenticloop' && statSync(fullPath).isDirectory()) {
        const children = readdirSync(fullPath);
        const hasUnknownContent = children.some(child => {
          const childPath = join(fullPath, child);
          const isCodexPlugin = child === '.codex-plugin';
          const isCursorPlugin = child === '.cursor-plugin';
          const isSkillsDir = child === 'skills';
          return !isCodexPlugin && !isCursorPlugin && !isSkillsDir;
        });
        if (hasUnknownContent) {
          skipped.push(`${toDisplayPath(relPath)} (preserved; contains files not generated by Agentic Loop)`);
          continue;
        }
      }

      if (!dryRun) rmSync(fullPath, { recursive: true, force: true });
      removed.push(toDisplayPath(relPath));
      if (relPath === 'plugins/agenticloop') {
        removeEmptyParents(targetRoot, dirname(fullPath), removed, dryRun);
      }
    } catch (error) {
      errors.push(`${toDisplayPath(relPath)}: ${error.message}`);
    }
  }
}

function removeOwnedLegacyCanonicalAssets(targetRoot, removed, skipped, errors, dryRun) {
  for (const asset of inspectLegacyCanonicalAssets(targetRoot)) {
    const fullPath = resolve(targetRoot, asset.legacyPath);
    if (!asset.owned) {
      skipped.push(`${asset.legacyPath} (legacy root path preserved; ownership not confirmed)`);
      continue;
    }
    try {
      assertInsideTarget(targetRoot, fullPath);
      if (!dryRun) rmSync(fullPath, { recursive: true, force: true });
      removed.push(toDisplayPath(asset.legacyPath));
    } catch (error) {
      errors.push(`${asset.legacyPath}: ${error.message}`);
    }
  }
}

function maybeRemoveTargetState(targetRoot, removed, skipped, errors, dryRun, includeState) {
  const statePath = join(targetRoot, TARGET_STATE_DIRECTORY);
  if (!existsSync(statePath)) return;
  if (!includeState) {
    skipped.push('.agenticloop/ (preserved target-owned state)');
    return;
  }
  try {
    assertInsideTarget(targetRoot, statePath);
    if (!dryRun) rmSync(statePath, { recursive: true, force: true });
    removed.push('.agenticloop');
  } catch (error) {
    errors.push(`.agenticloop: ${error.message}`);
  }
}

/**
 * Remove known Agentic Loop assets.
 *
 * @param {object} options
 * @param {string} options.target
 * @param {boolean} options.dryRun
 * @param {boolean} [options.includeState=false]
 * @returns {{ removed: string[], skipped: string[], errors: string[] }}
 */
export function removeAgenticLoop(options) {
  const targetRoot = resolve(options.target ?? process.cwd());
  const dryRun = Boolean(options.dryRun);
  const includeState = Boolean(options.includeState);
  const removed = [];
  const skipped = [];
  const errors = [];

  if (isPackageSourceRepositoryRoot(targetRoot)) {
    errors.push(
      `Refusing to mutate the Agentic Loop package source repository at ${targetRoot}. Use --target to point at a downstream project directory.`
    );
    return { removed, skipped, errors };
  }

  removeKnownPaths(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedOpencodeFiles(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedCodexAgentFiles(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedClaudeCodeFiles(targetRoot, removed, skipped, errors, dryRun);
  removeOwnedLegacyCanonicalAssets(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedCodexSkillDirs(targetRoot, removed, skipped, errors, dryRun);
  removeAgenticLoopMarketplaceEntry(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedCopilotArtifacts(targetRoot, removed, skipped, errors, dryRun);
  removeGeneratedCursorArtifacts(targetRoot, removed, skipped, errors, dryRun);
  maybeRemoveTargetState(targetRoot, removed, skipped, errors, dryRun, includeState);

  return { removed, skipped, errors };
}
